// Generated by tools/quelvra-advanced-oracle.py (sympy/mpmath as an OFFLINE oracle only). Do not edit by hand.
// 226 cases, 339 probes.
export const CORPUS = [
 {
  "area": "multivariable",
  "qs": [
   "pdiff(x^2*y^3, x, y)",
   "partial derivative of x^2 y^3 with respect to x and then y",
   "f_xy of x^2 y^3"
  ],
  "want": {
   "value": "6*x*y^2"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "pdiff(sin(x*y), x, x)",
   "second partial derivative of sin(x y) with respect to x"
  ],
  "want": {
   "value": "-y^2*sin(x*y)"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "pdiff(e^(x*y*z), x, y, z)"
  ],
  "want": {
   "value": "(x^2*y^2*z^2 + 3*x*y*z + 1)*exp(x*y*z)"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "pdiff(x^3*y^2 + y*z, y, y)",
   "f_yy for f = x^3 y^2 + y z"
  ],
  "want": {
   "value": "2*x^3"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "pdiff(ln(x^2 + y^2), x, y)"
  ],
  "want": {
   "value": "-4*x*y/(x^2 + y^2)^2"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "f_xy for f(x, y) = x^3 y + e^(x y)",
   "pdiff(x^3*y + e^(x*y), x, y)"
  ],
  "want": {
   "value": "3*x^2 + x*y*exp(x*y) + exp(x*y)"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "grad(x^2*y + y*z^2)",
   "gradient of x^2 y + y z^2"
  ],
  "want": {
   "vector": [
    "2*x*y",
    "x^2 + z^2",
    "2*y*z"
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "grad(x^2 + y^2, [x, y], [1, 2])",
   "gradient of x^2 + y^2 at (1, 2)"
  ],
  "want": {
   "vector": [
    "2",
    "4"
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "grad(e^x*sin(y))",
   "grad of e^x sin(y)"
  ],
  "want": {
   "vector": [
    "exp(x)*sin(y)",
    "exp(x)*cos(y)"
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "dirderiv(x^2*y, [3, 4], [1, 2])",
   "directional derivative of x^2 y at (1, 2) in the direction of (3, 4)"
  ],
  "want": {
   "value": "16/5"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "dirderiv(x*y*z, [1, 1, 1], [1, 2, 3])",
   "directional derivative of x y z at (1, 2, 3) in the direction <1, 1, 1>"
  ],
  "want": {
   "value": "11*sqrt(3)/3"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "dirderiv(x^2 + y^2, [1, 0])"
  ],
  "want": {
   "value": "2*x"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "jacobian([x^2*y, x + y], [x, y])",
   "jacobian of (x^2 y, x + y)"
  ],
  "want": {
   "matrix": [
    [
     "2*x*y",
     "x^2"
    ],
    [
     "1",
     "1"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "jacobian([r*cos(theta), r*sin(theta)], [r, theta])"
  ],
  "want": {
   "matrix": [
    [
     "cos(theta)",
     "-r*sin(theta)"
    ],
    [
     "sin(theta)",
     "r*cos(theta)"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "jacobiandet([r*cos(theta), r*sin(theta)], [r, theta])",
   "jacobian determinant of (r cos(theta), r sin(theta)) with respect to r and theta"
  ],
  "want": {
   "value": "r"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "jacobian([x*y*z, x + y + z, x*y], [x, y, z])"
  ],
  "want": {
   "matrix": [
    [
     "y*z",
     "x*z",
     "x*y"
    ],
    [
     "1",
     "1",
     "1"
    ],
    [
     "y",
     "x",
     "0"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "hessian(x^3 + x*y^2)",
   "hessian of x^3 + x y^2",
   "hessian matrix of f(x, y) = x^3 + x y^2"
  ],
  "want": {
   "matrix": [
    [
     "6*x",
     "2*y"
    ],
    [
     "2*y",
     "2*x"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "hessian(x^2*y + y^3 - z^2)"
  ],
  "want": {
   "matrix": [
    [
     "2*y",
     "2*x",
     "0"
    ],
    [
     "2*x",
     "6*y",
     "0"
    ],
    [
     "0",
     "0",
     "-2"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "laplacian(x^2 + y^2 + z^2)",
   "laplacian of x^2 + y^2 + z^2"
  ],
  "want": {
   "value": "6"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "laplacian(e^x*sin(y))"
  ],
  "want": {
   "value": "0"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "laplacian(1/sqrt(x^2 + y^2 + z^2))"
  ],
  "want": {
   "value": "0"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "laplacian(x^3*y + y^3)"
  ],
  "want": {
   "value": "6*y*(x + 1)"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "totaldiff(x^2*y)",
   "total differential of x^2 y"
  ],
  "want": {
   "differential": {
    "x": "2*x*y",
    "y": "x^2"
   }
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "totaldiff(x*y*z)"
  ],
  "want": {
   "differential": {
    "x": "y*z",
    "y": "x*z",
    "z": "x*y"
   }
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "tangentplane(x^2 + y^2, [1, 2])",
   "tangent plane to z = x^2 + y^2 at (1, 2)"
  ],
  "want": {
   "plane": "z = 2x + 4y - 5"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "tangentplane(x^2 + y^2 + z^2 = 14, [1, 2, 3])",
   "tangent plane to the surface x^2 + y^2 + z^2 = 14 at (1, 2, 3)"
  ],
  "want": {
   "plane": "x + 2y + 3z = 14"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "tangentplane(e^x*cos(y), [0, 0])",
   "equation of the tangent plane to z = e^x cos(y) at (0, 0)"
  ],
  "want": {
   "plane": "z = 1 + x"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "tangentplane(x*y, [2, 3])"
  ],
  "want": {
   "plane": "z = 3x + 2y - 6"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "critical(x^3 - 3x + y^2)",
   "critical points of x^3 - 3x + y^2",
   "classify the critical points of f(x, y) = x^3 - 3x + y^2"
  ],
  "want": {
   "points": [
    [
     {
      "x": "1",
      "y": "0"
     },
     "min"
    ],
    [
     {
      "x": "-1",
      "y": "0"
     },
     "saddle"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "critical(x^2 + x*y + y^2 - 3x)",
   "local extrema of f(x, y) = x^2 + x y + y^2 - 3x"
  ],
  "want": {
   "points": [
    [
     {
      "x": "2",
      "y": "-1"
     },
     "min"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "critical(x^3 + y^3 - 3x*y)",
   "find and classify the critical points of x^3 + y^3 - 3 x y"
  ],
  "want": {
   "points": [
    [
     {
      "x": "0",
      "y": "0"
     },
     "saddle"
    ],
    [
     {
      "x": "1",
      "y": "1"
     },
     "min"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "critical(x^4 + y^4 - 4x*y + 1)"
  ],
  "want": {
   "points": [
    [
     {
      "x": "0",
      "y": "0"
     },
     "saddle"
    ],
    [
     {
      "x": "1",
      "y": "1"
     },
     "min"
    ],
    [
     {
      "x": "-1",
      "y": "-1"
     },
     "min"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "critical(x^2 - y^2)",
   "saddle points of f(x, y) = x^2 - y^2"
  ],
  "want": {
   "points": [
    [
     {
      "x": "0",
      "y": "0"
     },
     "saddle"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "critical(x*y*(1 - x - y))"
  ],
  "want": {
   "points": [
    [
     {
      "x": "0",
      "y": "0"
     },
     "saddle"
    ],
    [
     {
      "x": "1",
      "y": "0"
     },
     "saddle"
    ],
    [
     {
      "x": "0",
      "y": "1"
     },
     "saddle"
    ],
    [
     {
      "x": "1/3",
      "y": "1/3"
     },
     "max"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "critical(x^4 + y^4)"
  ],
  "want": {
   "points": [
    [
     {
      "x": "0",
      "y": "0"
     },
     "min|inconclusive"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "critical(2x^2 + y^2 + z^2 - 2x*z + 4)"
  ],
  "want": {
   "points": [
    [
     {
      "x": "0",
      "y": "0",
      "z": "0"
     },
     "min"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "lagrange(x*y, x^2 + y^2 = 1)",
   "maximize x y subject to x^2 + y^2 = 1",
   "use lagrange multipliers to find the extreme values of x y subject to x^2 + y^2 = 1"
  ],
  "want": {
   "extrema": {
    "max": "1/2",
    "min": "-1/2"
   }
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "lagrange(x + y, x^2 + y^2 = 2)",
   "extreme values of x + y subject to x^2 + y^2 = 2"
  ],
  "want": {
   "extrema": {
    "max": "2",
    "min": "-2"
   }
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "lagrange(x^2 + y^2, x + y = 1)",
   "minimize x^2 + y^2 subject to x + y = 1"
  ],
  "want": {
   "candidates": [
    [
     {
      "x": "1/2",
      "y": "1/2"
     },
     "1/2"
    ]
   ]
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "lagrange(x + 2y + 3z, x^2 + y^2 + z^2 = 14)"
  ],
  "want": {
   "extrema": {
    "max": "14",
    "min": "-14"
   }
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "find the extreme values of f(x, y) = x^2 + 2y^2 on the circle x^2 + y^2 = 1",
   "lagrange(x^2 + 2y^2, x^2 + y^2 = 1)"
  ],
  "want": {
   "extrema": {
    "max": "2",
    "min": "1"
   }
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "lagrange(x*y*z, x^2 + y^2 + z^2 = 3)"
  ],
  "want": {
   "extrema": {
    "max": "1",
    "min": "-1"
   }
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "dblint(x*y, x, 0, 1, y, 0, 2)",
   "double integral of x y over [0, 1] x [0, 2]",
   "integrate x y over the rectangle 0 <= x <= 1, 0 <= y <= 2"
  ],
  "want": {
   "value": "1"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "integrate(integrate(x^2 + y^2, x, 0, 1), y, 0, 1)"
  ],
  "want": {
   "value": "2/3"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "dblint(x*y, y, 0, x, x, 0, 1)",
   "double integral of x y for y from 0 to x and x from 0 to 1"
  ],
  "want": {
   "value": "1/8"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "dblint(e^(x + y), x, 0, 1, y, 0, 1)"
  ],
  "want": {
   "value": "-2*e + 1 + exp(2)"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "dblint(sin(x)*cos(y), x, 0, pi, y, 0, pi/2)",
   "double integral of sin(x) cos(y) over [0, pi] x [0, pi/2]"
  ],
  "want": {
   "value": "2"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "dblint(x + y, y, x^2, x, x, 0, 1)"
  ],
  "want": {
   "value": "3/20"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "dblint(x^2*y, x, 0, 2, y, 1, 3)"
  ],
  "want": {
   "value": "32/3"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "tplint(x*y*z, x, 0, 1, y, 0, 2, z, 0, 3)",
   "triple integral of x y z over the box [0, 1] x [0, 2] x [0, 3]"
  ],
  "want": {
   "value": "9/2"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "tplint(1, z, 0, x + y, y, 0, 1, x, 0, 1)"
  ],
  "want": {
   "value": "1"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "tplint(x + y + z, x, 0, 1, y, 0, 1, z, 0, 1)"
  ],
  "want": {
   "value": "3/2"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "polarint(x^2 + y^2, 0, 2, 0, 2pi)",
   "double integral of x^2 + y^2 over the disk x^2 + y^2 <= 4"
  ],
  "want": {
   "value": "8*pi"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "polarint(e^(-(x^2 + y^2)), 0, 1, 0, 2pi)",
   "integrate e^(-(x^2 + y^2)) over the unit disk using polar coordinates"
  ],
  "want": {
   "value": "-pi*exp(-1) + pi"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "polarint(1, 0, 2cos(theta), -pi/2, pi/2)"
  ],
  "want": {
   "value": "pi"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "polarint(r, 0, 1, 0, pi)"
  ],
  "want": {
   "value": "pi/3"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "cylint(z, 0, 1, 0, 2pi, 0, 2)"
  ],
  "want": {
   "value": "2*pi"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "sphint(1, 0, 2, 0, 2pi, 0, pi)",
   "triple integral of 1 over the ball x^2 + y^2 + z^2 <= 4"
  ],
  "want": {
   "value": "32*pi/3"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "sphint(x^2 + y^2 + z^2, 0, 1, 0, 2pi, 0, pi)",
   "integrate x^2 + y^2 + z^2 over the unit ball in spherical coordinates"
  ],
  "want": {
   "value": "4*pi/5"
  }
 },
 {
  "area": "multivariable",
  "qs": [
   "critical(sin(x)*sin(y))"
  ],
  "want": {
   "refuse": true
  }
 },
 {
  "area": "vector",
  "qs": [
   "div([x^2, y*z, x*z])",
   "divergence of <x^2, y z, x z>"
  ],
  "want": {
   "value": "3*x + z"
  }
 },
 {
  "area": "vector",
  "qs": [
   "div([x*y, y*z, z*x])",
   "div of (x y, y z, z x)"
  ],
  "want": {
   "value": "x + y + z"
  }
 },
 {
  "area": "vector",
  "qs": [
   "div([x, y])"
  ],
  "want": {
   "value": "2"
  }
 },
 {
  "area": "vector",
  "qs": [
   "div([x*e^y, y*e^z, z*e^x])"
  ],
  "want": {
   "value": "exp(x) + exp(y) + exp(z)"
  }
 },
 {
  "area": "vector",
  "qs": [
   "curl([y, -x, 0])",
   "curl of (y, -x, 0)"
  ],
  "want": {
   "vector": [
    "0",
    "0",
    "-2"
   ]
  }
 },
 {
  "area": "vector",
  "qs": [
   "curl([x*y, y*z, z*x])",
   "curl of F = <x y, y z, z x>"
  ],
  "want": {
   "vector": [
    "-y",
    "-z",
    "-x"
   ]
  }
 },
 {
  "area": "vector",
  "qs": [
   "curl([x^2, y^2, z^2])"
  ],
  "want": {
   "vector": [
    "0",
    "0",
    "0"
   ]
  }
 },
 {
  "area": "vector",
  "qs": [
   "curl([-y, x])"
  ],
  "want": {
   "value": "2"
  }
 },
 {
  "area": "vector",
  "qs": [
   "lineint([y, x], [t, t^2], t, 0, 1)",
   "line integral of F = <y, x> along r(t) = (t, t^2) for t from 0 to 1"
  ],
  "want": {
   "value": "1"
  }
 },
 {
  "area": "vector",
  "qs": [
   "lineint([-y, x], [cos(t), sin(t)], t, 0, 2pi)",
   "work done by F = (-y, x) along r(t) = (cos t, sin t) from t = 0 to 2pi"
  ],
  "want": {
   "value": "2*pi"
  }
 },
 {
  "area": "vector",
  "qs": [
   "lineint(x*y, [cos(t), sin(t)], t, 0, pi/2)",
   "line integral of x y ds along r(t) = (cos t, sin t) from t = 0 to pi/2"
  ],
  "want": {
   "value": "1/2"
  }
 },
 {
  "area": "vector",
  "qs": [
   "lineint(x + y + z, [t, 2t, 3t], t, 0, 1)"
  ],
  "want": {
   "value": "3*sqrt(14)"
  }
 },
 {
  "area": "vector",
  "qs": [
   "lineint([y*z, x*z, x*y], [t, t^2, t^3], t, 0, 1)"
  ],
  "want": {
   "value": "1"
  }
 },
 {
  "area": "vector",
  "qs": [
   "lineint([x^2, x*y], [t, t], t, 0, 1)"
  ],
  "want": {
   "value": "2/3"
  }
 },
 {
  "area": "vector",
  "qs": [
   "conservative([2*x*y, x^2])",
   "is F = <2 x y, x^2> conservative"
  ],
  "want": {
   "bool": true,
   "potential": "x^2*y"
  }
 },
 {
  "area": "vector",
  "qs": [
   "conservative([y, -x])",
   "is the vector field (y, -x) conservative"
  ],
  "want": {
   "bool": false
  }
 },
 {
  "area": "vector",
  "qs": [
   "potential([2*x*y + z^2, x^2, 2*x*z])",
   "find a potential function for F = (2 x y + z^2, x^2, 2 x z)"
  ],
  "want": {
   "potential": "x^2*y + x*z^2"
  }
 },
 {
  "area": "vector",
  "qs": [
   "potential([y*cos(x*y), x*cos(x*y)])"
  ],
  "want": {
   "potential": "sin(x*y)"
  }
 },
 {
  "area": "vector",
  "qs": [
   "conservative([y*z, x*z, x*y])"
  ],
  "want": {
   "bool": true,
   "potential": "x*y*z"
  }
 },
 {
  "area": "vector",
  "qs": [
   "potential([y, -x])"
  ],
  "want": {
   "refuse": true
  }
 },
 {
  "area": "vector",
  "qs": [
   "flux([x, y, z], [sin(u)*cos(v), sin(u)*sin(v), cos(u)], u, 0, pi, v, 0, 2pi)",
   "flux of F = <x, y, z> through the unit sphere"
  ],
  "want": {
   "value": "4*pi"
  }
 },
 {
  "area": "vector",
  "qs": [
   "flux of F = <x, y, z> through the sphere of radius 2"
  ],
  "want": {
   "value": "32*pi"
  }
 },
 {
  "area": "vector",
  "qs": [
   "flux([x, y, z], [u, v, 2], u, 0, 1, v, 0, 1)"
  ],
  "want": {
   "value": "2"
  }
 },
 {
  "area": "vector",
  "qs": [
   "surfint(1, [u*cos(v), u*sin(v), u], u, 0, 1, v, 0, 2pi)"
  ],
  "want": {
   "value": "sqrt(2)*pi"
  }
 },
 {
  "area": "vector",
  "qs": [
   "surfint(z^2, [sin(u)*cos(v), sin(u)*sin(v), cos(u)], u, 0, pi, v, 0, 2pi)",
   "surface integral of z^2 over the unit sphere"
  ],
  "want": {
   "value": "4*pi/3"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "laplace(t^2)",
   "laplace transform of t^2"
  ],
  "want": {
   "value": "2/s^3"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "laplace(e^(3t))",
   "laplace transform of e^(3t)"
  ],
  "want": {
   "value": "1/(s - 3)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "laplace(sin(2t))",
   "find the laplace transform of sin(2t)"
  ],
  "want": {
   "value": "2/(s^2 + 4)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "laplace(t*e^(-t))"
  ],
  "want": {
   "value": "(s + 1)^(-2)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "laplace(e^(2t)*cos(3t))",
   "laplace transform of e^(2t) cos(3t)"
  ],
  "want": {
   "value": "(s - 2)/((s - 2)^2 + 9)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "laplace(t*sin(t))"
  ],
  "want": {
   "value": "2*s/(s^4 + 2*s^2 + 1)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "laplace(cosh(2t))"
  ],
  "want": {
   "value": "s/(s^2 - 4)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "laplace(3 + 2t - e^(-t))"
  ],
  "want": {
   "value": "(2*s^2 + 5*s + 2)/(s^2*(s + 1))"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "laplace(heaviside(t - 2))",
   "laplace transform of heaviside(t - 2)"
  ],
  "want": {
   "value": "exp(-2*s)/s"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "laplace(sin(t)^2)"
  ],
  "want": {
   "value": "2/(s*(s^2 + 4))"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "laplace(t^3*e^(2t))"
  ],
  "want": {
   "value": "6/(s - 2)^4"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "laplace(e^(t^2))"
  ],
  "want": {
   "refuse": true
  }
 },
 {
  "area": "transforms",
  "qs": [
   "invlaplace(1/(s^2 + 4))",
   "inverse laplace transform of 1/(s^2 + 4)"
  ],
  "want": {
   "value": "sin(2*t)/2"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "invlaplace(1/(s*(s + 1)))",
   "inverse laplace of 1/(s(s + 1))"
  ],
  "want": {
   "value": "1 - exp(-t)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "invlaplace((s + 1)/(s^2 + 2s + 5))"
  ],
  "want": {
   "value": "exp(-t)*cos(2*t)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "invlaplace(1/(s - 2)^3)"
  ],
  "want": {
   "value": "t^2*exp(2*t)/2"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "invlaplace(5/(s^2 - 1))"
  ],
  "want": {
   "value": "5*sinh(t)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "invlaplace((2s + 3)/(s^2 + 9))",
   "find the inverse laplace transform of (2s + 3)/(s^2 + 9)"
  ],
  "want": {
   "value": "sin(3*t) + 2*cos(3*t)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "invlaplace(1/(s^2 + 1)^2)"
  ],
  "want": {
   "value": "-t*cos(t)/2 + sin(t)/2"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "invlaplace(e^(-s)/s^2)"
  ],
  "want": {
   "value": "(t - 1)*heaviside(t - 1)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "invlaplace(1/(s^3 + s))"
  ],
  "want": {
   "value": "1 - cos(t)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "invlaplace(ln(s))"
  ],
  "want": {
   "refuse": true
  }
 },
 {
  "area": "transforms",
  "qs": [
   "lapsolve(y'' + y = 0, y(0) = 1, y'(0) = 0)",
   "solve y'' + y = 0, y(0) = 1, y'(0) = 0 using laplace transforms"
  ],
  "want": {
   "value": "cos(t)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "lapsolve(y' + 2y = 4, y(0) = 1)",
   "use the laplace transform to solve y' + 2y = 4 with y(0) = 1"
  ],
  "want": {
   "value": "2 - exp(-2*t)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "lapsolve(y'' + 3y' + 2y = e^t, y(0) = 1, y'(0) = 0)"
  ],
  "want": {
   "value": "(exp(3*t) + 9*exp(t) - 4)*exp(-2*t)/6"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "lapsolve(y'' + 4y = sin(t), y(0) = 0, y'(0) = 0)"
  ],
  "want": {
   "value": "sin(t)/3 - sin(2*t)/6"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "lapsolve(y'' - 2y' + y = 0, y(0) = 0, y'(0) = 1)"
  ],
  "want": {
   "value": "t*exp(t)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "fourier(x, x, pi)",
   "fourier series of x on [-pi, pi]"
  ],
  "want": {
   "fourier": {
    "a0": "0",
    "an": "0",
    "bn": "-2*(-1)^n/n"
   }
  }
 },
 {
  "area": "transforms",
  "qs": [
   "fourier(x^2, x, pi)",
   "fourier series of f(x) = x^2 on -pi < x < pi"
  ],
  "want": {
   "fourier": {
    "a0": "2*pi^2/3",
    "an": "4*(-1)^n/n^2",
    "bn": "0"
   }
  }
 },
 {
  "area": "transforms",
  "qs": [
   "fourier(abs(x), x, pi)",
   "fourier coefficients of |x| on [-pi, pi]"
  ],
  "want": {
   "fourier": {
    "a0": "pi",
    "an": "2*((-1)^n - 1)/(pi*n^2)",
    "bn": "0"
   }
  }
 },
 {
  "area": "transforms",
  "qs": [
   "fourier(piecewise(-1, x < 0, 1, x >= 0), x, pi)"
  ],
  "want": {
   "fourier": {
    "a0": "0",
    "an": "0",
    "bn": "2*(1 - (-1)^n)/(pi*n)"
   }
  }
 },
 {
  "area": "transforms",
  "qs": [
   "fourier(x, x, 1)",
   "fourier series of x on [-1, 1]"
  ],
  "want": {
   "fourier": {
    "a0": "0",
    "an": "0",
    "bn": "-2*(-1)^n/(pi*n)"
   }
  }
 },
 {
  "area": "transforms",
  "qs": [
   "fourier(e^x, x, pi)"
  ],
  "want": {
   "fourier": {
    "a0": "2*sinh(pi)/pi",
    "an": "2*(-1)^n*sinh(pi)/(pi*(n^2 + 1))",
    "bn": "-2*(-1)^n*n*sinh(pi)/(pi*(n^2 + 1))"
   }
  }
 },
 {
  "area": "transforms",
  "qs": [
   "fourier(x + x^2, x, pi)"
  ],
  "want": {
   "fourier": {
    "a0": "2*pi^2/3",
    "an": "4*(-1)^n/n^2",
    "bn": "-2*(-1)^n/n"
   }
  }
 },
 {
  "area": "transforms",
  "qs": [
   "fouriertransform(e^(-abs(t)))",
   "fourier transform of e^(-|t|)"
  ],
  "want": {
   "value": "2/(w^2 + 1)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "fouriertransform(e^(-t^2))",
   "fourier transform of e^(-t^2)"
  ],
  "want": {
   "value": "sqrt(pi)*exp(-w^2/4)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "fouriertransform(1/(1 + t^2))"
  ],
  "want": {
   "value": "pi*exp(-abs(w))"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "fouriertransform(piecewise(1, abs(t) <= 1, 0, abs(t) > 1))"
  ],
  "want": {
   "value": "2*sin(w)/w"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "fouriertransform(e^(-2*abs(t)))"
  ],
  "want": {
   "value": "4/(w^2 + 4)"
  }
 },
 {
  "area": "transforms",
  "qs": [
   "fouriertransform(t)"
  ],
  "want": {
   "refuse": true
  }
 },
 {
  "area": "transforms",
  "qs": [
   "ztransform(2^n)",
   "z transform of 2^n"
  ],
  "want": {
   "value": "z/(z - 2)",
   "vars": {
    "z": [
     2.5,
     3.7,
     5.2,
     -4.1,
     6.3
    ]
   }
  }
 },
 {
  "area": "transforms",
  "qs": [
   "ztransform(n)",
   "z-transform of n"
  ],
  "want": {
   "value": "z/(z - 1)^2",
   "vars": {
    "z": [
     2.5,
     3.7,
     5.2,
     -4.1,
     6.3
    ]
   }
  }
 },
 {
  "area": "transforms",
  "qs": [
   "ztransform(1)"
  ],
  "want": {
   "value": "z/(z - 1)",
   "vars": {
    "z": [
     2.5,
     3.7,
     5.2,
     -4.1,
     6.3
    ]
   }
  }
 },
 {
  "area": "transforms",
  "qs": [
   "ztransform(n^2)"
  ],
  "want": {
   "value": "z*(z + 1)/(z - 1)^3",
   "vars": {
    "z": [
     2.5,
     3.7,
     5.2,
     -4.1,
     6.3
    ]
   }
  }
 },
 {
  "area": "transforms",
  "qs": [
   "ztransform(cos(pi*n/2))"
  ],
  "want": {
   "value": "z^2/(z^2 + 1)",
   "vars": {
    "z": [
     2.5,
     3.7,
     5.2,
     -4.1,
     6.3
    ]
   }
  }
 },
 {
  "area": "transforms",
  "qs": [
   "ztransform(n*3^n)"
  ],
  "want": {
   "value": "3*z/(z - 3)^2",
   "vars": {
    "z": [
     2.5,
     3.7,
     5.2,
     -4.1,
     6.3
    ]
   }
  }
 },
 {
  "area": "transforms",
  "qs": [
   "ztransform((1/2)^n + n)"
  ],
  "want": {
   "value": "z/(z - 1/2) + z/(z - 1)^2",
   "vars": {
    "z": [
     2.5,
     3.7,
     5.2,
     -4.1,
     6.3
    ]
   }
  }
 },
 {
  "area": "complex",
  "qs": [
   "residue(1/(z^2 + 1), z, i)",
   "residue of 1/(z^2 + 1) at z = i"
  ],
  "want": {
   "value": "-i/2",
   "complex": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "residue(e^z/z^3, z, 0)",
   "residue of e^z/z^3 at z = 0"
  ],
  "want": {
   "value": "1/2",
   "complex": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "residue(1/(z*(z - 1)^2), z, 1)"
  ],
  "want": {
   "value": "-1",
   "complex": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "residue(z/(z^2 - 3z + 2), z, 2)"
  ],
  "want": {
   "value": "2",
   "complex": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "residue(sin(z)/z^4, z, 0)"
  ],
  "want": {
   "value": "-1/6",
   "complex": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "residue(cos(z)/sin(z), z, 0)"
  ],
  "want": {
   "value": "1",
   "complex": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "residue(e^(2z)/(z - 1)^2, z, 1)",
   "find the residue of e^(2z)/(z - 1)^2 at z = 1"
  ],
  "want": {
   "value": "2*exp(2)",
   "complex": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "residue(1/(z^2 + 1), z)",
   "residues of 1/(z^2 + 1)"
  ],
  "want": {
   "residues": [
    [
     "i",
     "-i/2"
    ],
    [
     "-i",
     "i/2"
    ]
   ]
  }
 },
 {
  "area": "complex",
  "qs": [
   "laurent(e^z/z^2, z, 0, 2)",
   "laurent series of e^z/z^2 about z = 0"
  ],
  "want": {
   "laurent": "z/6 + 1/2 + 1/z + z^(-2)"
  }
 },
 {
  "area": "complex",
  "qs": [
   "laurent(1/(z*(z - 1)), z, 0, 2)"
  ],
  "want": {
   "laurent": "-z - 1 - 1/z"
  }
 },
 {
  "area": "complex",
  "qs": [
   "laurent(sin(z)/z^3, z, 0, 3)"
  ],
  "want": {
   "laurent": "z^2/120 - 1/6 + z^(-2)"
  }
 },
 {
  "area": "complex",
  "qs": [
   "laurent(1/(z^2 - 1), z, 1, 2)"
  ],
  "want": {
   "laurent": "z/8 - 3/8 + 1/(2*(z - 1))"
  }
 },
 {
  "area": "complex",
  "qs": [
   "contourint(1/z, z, 0, 1)",
   "integral of 1/z around |z| = 1",
   "contour integral of 1/z over the circle |z| = 1"
  ],
  "want": {
   "value": "2*i*pi",
   "complex": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "contourint(1/(z^2 + 1), z, 0, 2)",
   "integral of 1/(z^2 + 1) around |z| = 2"
  ],
  "want": {
   "value": "0",
   "complex": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "contourint(e^z/(z - 1), z, 0, 2)"
  ],
  "want": {
   "value": "2*e*i*pi",
   "complex": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "contourint(1/(z^2 + 1), z, i, 1)",
   "integral of 1/(z^2 + 1) around the circle |z - i| = 1"
  ],
  "want": {
   "value": "pi",
   "complex": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "contourint(z^2/(z - 2)^2, z, 0, 3)"
  ],
  "want": {
   "value": "8*i*pi",
   "complex": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "contourint(e^z/z^3, z, 0, 1)"
  ],
  "want": {
   "value": "i*pi",
   "complex": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "contourint(1/(z - 1), z, 0, 1)"
  ],
  "want": {
   "refuse": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "residueint(1/(x^2 + 1))",
   "integral of 1/(x^2 + 1) from -infinity to infinity using residues"
  ],
  "want": {
   "value": "pi"
  }
 },
 {
  "area": "complex",
  "qs": [
   "residueint(1/(x^4 + 1))",
   "evaluate the integral of 1/(x^4 + 1) from -infinity to infinity by residues"
  ],
  "want": {
   "value": "sqrt(2)*pi/2"
  }
 },
 {
  "area": "complex",
  "qs": [
   "residueint(1/(x^2 + 4)^2)"
  ],
  "want": {
   "value": "pi/16"
  }
 },
 {
  "area": "complex",
  "qs": [
   "residueint(cos(x)/(x^2 + 1))"
  ],
  "want": {
   "value": "pi*exp(-1)"
  }
 },
 {
  "area": "complex",
  "qs": [
   "residueint(x^2/(x^4 + 1))"
  ],
  "want": {
   "value": "sqrt(2)*pi/2"
  }
 },
 {
  "area": "complex",
  "qs": [
   "residueint(cos(2x)/(x^2 + 9))"
  ],
  "want": {
   "value": "pi*exp(-6)/3"
  }
 },
 {
  "area": "complex",
  "qs": [
   "residueint(x/(x^2 + 1))"
  ],
  "want": {
   "refuse": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "analytic(z^2)",
   "is f(z) = z^2 analytic"
  ],
  "want": {
   "bool": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "analytic(conj(z))",
   "is conj(z) analytic"
  ],
  "want": {
   "bool": false
  }
 },
 {
  "area": "complex",
  "qs": [
   "cauchyriemann(x^2 - y^2, 2*x*y)",
   "check the cauchy-riemann equations for u = x^2 - y^2 and v = 2 x y"
  ],
  "want": {
   "bool": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "analytic(e^z)"
  ],
  "want": {
   "bool": true
  }
 },
 {
  "area": "complex",
  "qs": [
   "cauchyriemann(x^2 + y^2, 2*x*y)"
  ],
  "want": {
   "bool": false,
   "where": "y = 0"
  }
 },
 {
  "area": "complex",
  "qs": [
   "analytic(abs(z)^2)"
  ],
  "want": {
   "bool": false,
   "where": "x = 0 and y = 0"
  }
 },
 {
  "area": "numerical",
  "qs": [
   "newton(x^3 - 2x - 5, x, 2)",
   "use newton's method to find a root of x^3 - 2x - 5 starting at x0 = 2"
  ],
  "want": {
   "approx": 2.0945514815423265,
   "tol": 1e-08
  }
 },
 {
  "area": "numerical",
  "qs": [
   "newton(cos(x) - x, x, 1)",
   "newton's method for cos(x) = x with x0 = 1"
  ],
  "want": {
   "approx": 0.7390851332151607,
   "tol": 1e-08
  }
 },
 {
  "area": "numerical",
  "qs": [
   "newton(x^2 - 2, x, 1)"
  ],
  "want": {
   "approx": 1.4142135623730951,
   "tol": 1e-08
  }
 },
 {
  "area": "numerical",
  "qs": [
   "use newton's method to solve e^x = 3x starting from x0 = 0",
   "newton(e^x - 3x, x, 0)"
  ],
  "want": {
   "approx": 0.6190612867359451,
   "tol": 1e-08
  }
 },
 {
  "area": "numerical",
  "qs": [
   "newton(x^2 - 4x + 4, x, 1)"
  ],
  "want": {
   "approx": 2.0,
   "tol": 1e-06
  }
 },
 {
  "area": "numerical",
  "qs": [
   "bisection(x^3 - x - 2, x, 1, 2)",
   "use the bisection method to find a root of x^3 - x - 2 on [1, 2]"
  ],
  "want": {
   "approx": 1.5213797068045676,
   "tol": 1e-08
  }
 },
 {
  "area": "numerical",
  "qs": [
   "bisection(cos(x) - x, x, 0, 1)"
  ],
  "want": {
   "approx": 0.7390851332151607,
   "tol": 1e-08
  }
 },
 {
  "area": "numerical",
  "qs": [
   "bisection(x^2 + 1, x, -1, 1)"
  ],
  "want": {
   "refuse": true
  }
 },
 {
  "area": "numerical",
  "qs": [
   "secant(x^2 - 612, x, 10, 30)",
   "secant method for x^2 - 612 with x0 = 10 and x1 = 30"
  ],
  "want": {
   "approx": 24.73863375370596,
   "tol": 1e-08
  }
 },
 {
  "area": "numerical",
  "qs": [
   "secant(x^3 - x - 1, x, 1, 2)"
  ],
  "want": {
   "approx": 1.324717957244746,
   "tol": 1e-08
  }
 },
 {
  "area": "numerical",
  "qs": [
   "fixedpoint(cos(x), x, 1)",
   "fixed point iteration for x = cos(x) starting at x0 = 1"
  ],
  "want": {
   "approx": 0.7390851332151607,
   "tol": 1e-08
  }
 },
 {
  "area": "numerical",
  "qs": [
   "fixedpoint((x + 2/x)/2, x, 1)"
  ],
  "want": {
   "approx": 1.4142135623730951,
   "tol": 1e-08
  }
 },
 {
  "area": "numerical",
  "qs": [
   "trapezoid(x^2, x, 0, 1, 4)",
   "trapezoidal rule for x^2 from 0 to 1 with n = 4"
  ],
  "want": {
   "approx": 0.34375,
   "tol": 1e-12
  }
 },
 {
  "area": "numerical",
  "qs": [
   "simpson(x^4, x, 0, 1, 4)",
   "simpson's rule for x^4 from 0 to 1 with n = 4"
  ],
  "want": {
   "approx": 0.20052083333333334,
   "tol": 1e-12
  }
 },
 {
  "area": "numerical",
  "qs": [
   "simpson(sin(x), x, 0, pi, 6)"
  ],
  "want": {
   "approx": 2.0008631896735363,
   "tol": 1e-12
  }
 },
 {
  "area": "numerical",
  "qs": [
   "trapezoid(e^x, x, 0, 1, 10)"
  ],
  "want": {
   "approx": 1.7197134913893144,
   "tol": 1e-12
  }
 },
 {
  "area": "numerical",
  "qs": [
   "use simpson's rule with n = 4 to approximate the integral of 1/(1 + x^2) from 0 to 1",
   "simpson(1/(1 + x^2), x, 0, 1, 4)"
  ],
  "want": {
   "approx": 0.7853921568627451,
   "tol": 1e-12
  }
 },
 {
  "area": "numerical",
  "qs": [
   "eulermethod(x + y, x, y, 0, 1, 0.1, 1)",
   "use euler's method with h = 0.1 to approximate y(1) for y' = x + y, y(0) = 1"
  ],
  "want": {
   "approx": 3.1874849202,
   "tol": 1e-10
  }
 },
 {
  "area": "numerical",
  "qs": [
   "eulermethod(y, t, y, 0, 1, 0.25, 1)"
  ],
  "want": {
   "approx": 2.44140625,
   "tol": 1e-10
  }
 },
 {
  "area": "numerical",
  "qs": [
   "rungekutta(x + y, x, y, 0, 1, 0.1, 1)",
   "use rk4 with h = 0.1 to approximate y(1) where y' = x + y and y(0) = 1"
  ],
  "want": {
   "approx": 3.436559488270331,
   "tol": 1e-10
  }
 },
 {
  "area": "numerical",
  "qs": [
   "rungekutta(-2*t*y, t, y, 0, 1, 0.1, 1)"
  ],
  "want": {
   "approx": 0.3678810664257649,
   "tol": 1e-10
  }
 },
 {
  "area": "numerical",
  "qs": [
   "use euler's method with step size 0.1 to approximate y(0.5) where y' = x^2 + y, y(0) = 1",
   "eulermethod(x^2 + y, x, y, 0, 1, 0.1, 0.5)"
  ],
  "want": {
   "approx": 1.642581,
   "tol": 1e-10
  }
 },
 {
  "area": "numerical",
  "qs": [
   "poweriter([[2, 1], [1, 3]])",
   "power method for the matrix [[2, 1], [1, 3]]"
  ],
  "want": {
   "approx": 3.618033988749895,
   "tol": 1e-08
  }
 },
 {
  "area": "numerical",
  "qs": [
   "poweriter([[4, 1], [2, 3]])"
  ],
  "want": {
   "approx": 5.0,
   "tol": 1e-08
  }
 },
 {
  "area": "numerical",
  "qs": [
   "poweriter([[2, 0, 0], [0, 3, 4], [0, 4, 9]])"
  ],
  "want": {
   "approx": 11.0,
   "tol": 1e-08
  }
 },
 {
  "area": "curves",
  "qs": [
   "curvature([cos(t), sin(t), t], t)",
   "curvature of r(t) = (cos t, sin t, t)"
  ],
  "want": {
   "value": "1/2"
  }
 },
 {
  "area": "curves",
  "qs": [
   "curvature(x^2, x, 1)",
   "curvature of y = x^2 at x = 1"
  ],
  "want": {
   "value": "2*sqrt(5)/25"
  }
 },
 {
  "area": "curves",
  "qs": [
   "curvature([t, t^2], t, 0)"
  ],
  "want": {
   "value": "2"
  }
 },
 {
  "area": "curves",
  "qs": [
   "curvature([3cos(t), 3sin(t)], t)",
   "curvature of the circle r(t) = (3 cos t, 3 sin t)"
  ],
  "want": {
   "value": "1/3"
  }
 },
 {
  "area": "curves",
  "qs": [
   "curvature(sin(x), x, pi/2)"
  ],
  "want": {
   "value": "1"
  }
 },
 {
  "area": "curves",
  "qs": [
   "curvature([t, t^2, t^3], t, 0)"
  ],
  "want": {
   "value": "2"
  }
 },
 {
  "area": "curves",
  "qs": [
   "curvature(ln(x), x, 1)"
  ],
  "want": {
   "value": "sqrt(2)/4"
  }
 },
 {
  "area": "curves",
  "qs": [
   "curvature(x^3, x)"
  ],
  "want": {
   "value": "6*abs(x)/(9*x^4 + 1)^(3/2)"
  }
 },
 {
  "area": "curves",
  "qs": [
   "torsion([cos(t), sin(t), t], t)",
   "torsion of r(t) = (cos t, sin t, t)"
  ],
  "want": {
   "value": "1/2"
  }
 },
 {
  "area": "curves",
  "qs": [
   "torsion([t, t^2, t^3], t, 0)"
  ],
  "want": {
   "value": "3"
  }
 },
 {
  "area": "curves",
  "qs": [
   "torsion([t, t^2, 0], t)"
  ],
  "want": {
   "value": "0"
  }
 },
 {
  "area": "curves",
  "qs": [
   "unittangent([cos(t), sin(t), t], t)",
   "unit tangent vector of r(t) = (cos t, sin t, t)"
  ],
  "want": {
   "vector": [
    "-sqrt(2)*sin(t)/2",
    "sqrt(2)*cos(t)/2",
    "sqrt(2)/2"
   ]
  }
 },
 {
  "area": "curves",
  "qs": [
   "unitnormal([cos(t), sin(t), t], t)",
   "principal unit normal of r(t) = (cos t, sin t, t)"
  ],
  "want": {
   "vector": [
    "-cos(t)",
    "-sin(t)",
    "0"
   ]
  }
 },
 {
  "area": "curves",
  "qs": [
   "binormal([cos(t), sin(t), t], t)",
   "binormal vector of r(t) = (cos t, sin t, t)"
  ],
  "want": {
   "vector": [
    "sqrt(2)*sin(t)/2",
    "-sqrt(2)*cos(t)/2",
    "sqrt(2)/2"
   ]
  }
 },
 {
  "area": "curves",
  "qs": [
   "unittangent([t, t^2], t, 1)"
  ],
  "want": {
   "vector": [
    "sqrt(5)/5",
    "2*sqrt(5)/5"
   ]
  }
 },
 {
  "area": "curves",
  "qs": [
   "arclength([cos(t), sin(t), t], t, 0, 2pi)",
   "arc length of r(t) = (cos t, sin t, t) from t = 0 to 2pi"
  ],
  "want": {
   "value": "2*sqrt(2)*pi"
  }
 },
 {
  "area": "curves",
  "qs": [
   "arclength([t^2, t^3], t, 0, 1)"
  ],
  "want": {
   "value": "-8/27 + 13*sqrt(13)/27"
  }
 },
 {
  "area": "curves",
  "qs": [
   "arcparam([3cos(t), 3sin(t), 4t], t)",
   "arc length parametrization of r(t) = (3 cos t, 3 sin t, 4t)"
  ],
  "want": {
   "vector": [
    "3*cos(s/5)",
    "3*sin(s/5)",
    "4*s/5"
   ],
   "label": "r(s)"
  }
 },
 {
  "area": "curves",
  "qs": [
   "arcparam([t, t], t)"
  ],
  "want": {
   "vector": [
    "sqrt(2)*s/2",
    "sqrt(2)*s/2"
   ],
   "label": "r(s)"
  }
 },
 {
  "area": "pde",
  "qs": [
   "pdecheck(e^(-t)*sin(x), u_t = u_xx)",
   "verify that u = e^(-t) sin(x) satisfies u_t = u_xx"
  ],
  "want": {
   "bool": true
  }
 },
 {
  "area": "pde",
  "qs": [
   "pdecheck(sin(x - 2t), u_tt = 4u_xx)",
   "does u = sin(x - 2t) satisfy u_tt = 4 u_xx"
  ],
  "want": {
   "bool": true
  }
 },
 {
  "area": "pde",
  "qs": [
   "pdecheck(x^2 - y^2, u_xx + u_yy = 0)",
   "show that u = x^2 - y^2 satisfies u_xx + u_yy = 0"
  ],
  "want": {
   "bool": true
  }
 },
 {
  "area": "pde",
  "qs": [
   "pdecheck(x^2 + y^2, u_xx + u_yy = 0)"
  ],
  "want": {
   "bool": false
  }
 },
 {
  "area": "pde",
  "qs": [
   "pdecheck(e^(-4t)*sin(2x), u_t = u_xx)"
  ],
  "want": {
   "bool": true
  }
 },
 {
  "area": "pde",
  "qs": [
   "pdecheck(e^(-t)*sin(x), u_t = 2u_xx)"
  ],
  "want": {
   "bool": false
  }
 },
 {
  "area": "pde",
  "qs": [
   "classifypde(u_xx + 2u_xy + u_yy = 0)",
   "classify the pde u_xx + 2 u_xy + u_yy = 0"
  ],
  "want": {
   "type": "parabolic"
  }
 },
 {
  "area": "pde",
  "qs": [
   "classifypde(u_xx - 4u_yy = 0)",
   "classify u_xx - 4 u_yy = 0"
  ],
  "want": {
   "type": "hyperbolic"
  }
 },
 {
  "area": "pde",
  "qs": [
   "classifypde(u_xx + u_yy = 0)"
  ],
  "want": {
   "type": "elliptic"
  }
 },
 {
  "area": "pde",
  "qs": [
   "classifypde(3u_xx + 2u_xy + 5u_yy + u_x = 0)"
  ],
  "want": {
   "type": "elliptic"
  }
 },
 {
  "area": "pde",
  "qs": [
   "classifypde(u_xx + x*u_yy = 0)",
   "classify the pde u_xx + x u_yy = 0"
  ],
  "want": {
   "regions": {
    "elliptic": "x > 0",
    "hyperbolic": "x < 0",
    "parabolic": "x = 0"
   }
  }
 },
 {
  "area": "pde",
  "qs": [
   "heat(sin(pi*x), x, t, 1, 1)",
   "solve the heat equation u_t = u_xx on 0 < x < 1 with u(0, t) = u(1, t) = 0 and u(x, 0) = sin(pi x)"
  ],
  "want": {
   "value": "exp(-pi^2*t)*sin(pi*x)",
   "label": "u(x, t)"
  }
 },
 {
  "area": "pde",
  "qs": [
   "heat(x*(1 - x), x, t, 1, 1)",
   "heat equation u_t = u_xx on [0, 1] with zero boundary conditions and u(x, 0) = x(1 - x)"
  ],
  "want": {
   "bn": "4*(1 - (-1)^n)/(pi^3*n^3)"
  }
 },
 {
  "area": "pde",
  "qs": [
   "heat(1, x, t, pi, 1)"
  ],
  "want": {
   "bn": "2*(1 - (-1)^n)/(pi*n)"
  }
 },
 {
  "area": "pde",
  "qs": [
   "heat(x, x, t, 2, 3)"
  ],
  "want": {
   "bn": "-4*(-1)^n/(pi*n)"
  }
 },
 {
  "area": "pde",
  "qs": [
   "wave(sin(pi*x), 0, x, t, 1, 1)",
   "solve the wave equation u_tt = u_xx on 0 < x < 1 with u(0, t) = u(1, t) = 0, u(x, 0) = sin(pi x) and u_t(x, 0) = 0"
  ],
  "want": {
   "value": "sin(pi*x)*cos(pi*t)",
   "label": "u(x, t)"
  }
 },
 {
  "area": "pde",
  "qs": [
   "wave(0, sin(pi*x), x, t, 1, 2)"
  ],
  "want": {
   "value": "sin(2*pi*t)*sin(pi*x)/(2*pi)",
   "label": "u(x, t)"
  }
 },
 {
  "area": "pde",
  "qs": [
   "wave(x*(1 - x), 0, x, t, 1, 1)"
  ],
  "want": {
   "an": "4*(1 - (-1)^n)/(pi^3*n^3)"
  }
 }
];
