// Word-problem corpus: realistic problems of the kind students type, written before the language
// work on them (see tools/quelvra-words.mjs for the per-category report). Expected answers were
// worked by hand. Each case: [category, input, expectation]
//   number          the quantity the question asks for (one shown answer must equal it)
//   { nums: [...] } the set of values the question asks for (every one shown, nothing else numeric)
// Verdicts (wordproblems.judge.js): ok, incomplete (a correct subset, e.g. only the smallest of three
// consecutive integers), refused, WRONG. A refusal is acceptable; a WRONG answer never is.
const PI = Math.PI;
export const CASES = [
  // ---------------------------------------------------------------- ages
  ["age", "John is twice as old as Mary. In 5 years the sum of their ages will be 40. How old is Mary?", 10],
  ["age", "Sarah is 4 years older than her brother. The sum of their ages is 30. How old is her brother?", 13],
  ["age", "A father is 3 times as old as his son. In 12 years he will be twice as old as his son. How old is the son now?", 12],
  ["age", "Tom is 6 years older than Jerry. In 4 years Tom will be twice as old as Jerry. How old is Jerry now?", 2],
  ["age", "The sum of the ages of a mother and her daughter is 50. The mother is 20 years older than the daughter. How old is the daughter?", 15],
  ["age", "Five years ago, Lisa was twice as old as Sam. Sam is 12 now. How old is Lisa now?", 19],
  ["age", "Mike is 3 times as old as his daughter. The sum of their ages is 48. How old is Mike?", 36],
  ["age", "In 6 years Anna will be 20. How old is Anna now?", 14],
  ["age", "Peter's age is 5 more than twice Paul's age. The sum of their ages is 35. How old is Paul?", 10],
  ["age", "A mother is 24 years older than her son. In 6 years, she will be 3 times as old as her son. How old is the son now?", 6],
  ["age", "Emma is 8 years younger than her sister. The sum of their ages is 36. How old is Emma?", 14],
  ["age", "The ratio of Amy's age to Ben's age is 3:4. Ben is 28. How old is Amy?", 21],

  // ---------------------------------------------------------------- mixtures
  ["mixture", "How many liters of a 20% acid solution must be added to 10 liters of a 50% acid solution to get a 30% acid solution?", 20],
  ["mixture", "How many liters of water must be added to 12 liters of a 40% salt solution to make a 30% solution?", 4],
  ["mixture", "A chemist mixes a 10% solution with a 40% solution to get 30 liters of a 20% solution. How many liters of the 10% solution are used?", 20],
  ["mixture", "Coffee worth $6 per pound is mixed with coffee worth $10 per pound to make 20 pounds worth $7 per pound. How many pounds of the $6 coffee are used?", 15],
  ["mixture", "How much pure alcohol must be added to 8 liters of a 25% alcohol solution to get a 40% solution?", 2],
  ["mixture", "How many ml of a 5% saline solution should be mixed with 200 ml of a 15% saline solution to get a 12% solution?", 600 / 7],
  ["mixture", "Nuts costing $4 per kg are mixed with nuts costing $7 per kg. How many kg of each are needed to make 30 kg of a mixture costing $5 per kg?", { nums: [20, 10] }],
  ["mixture", "A 60 liter mixture is 30% juice. How much juice must be added to make it 50% juice?", 24],
  ["mixture", "A farmer has 100 liters of milk that is 4% butterfat. How much cream that is 20% butterfat should be added to get milk that is 6% butterfat?", 100 / 7],
  ["mixture", "How many gallons of a 30% antifreeze solution and a 60% antifreeze solution must be mixed to obtain 12 gallons of a 50% solution?", { nums: [4, 8] }],
  ["mixture", "How much water should be evaporated from 50 liters of a 10% salt solution to make a 25% salt solution?", 30],
  ["mixture", "Candy worth $2 per pound is mixed with 10 pounds of candy worth $5 per pound. How many pounds of the $2 candy are needed to make a mixture worth $3 per pound?", 20],

  // ---------------------------------------------------------------- work and rates
  ["work", "Alice can paint a room in 4 hours and Bob can paint it in 6 hours. How long will it take them working together?", 2.4],
  ["work", "One pipe can fill a tank in 3 hours and another pipe can fill it in 6 hours. How long will it take both pipes together to fill the tank?", 2],
  ["work", "A pipe can fill a pool in 5 hours and a drain can empty it in 10 hours. If both are open, how long will it take to fill the pool?", 10],
  ["work", "Working together, two machines finish a job in 6 hours. One machine alone takes 10 hours. How long does the other machine take alone?", 15],
  ["work", "John can mow a lawn in 2 hours and his son can mow it in 3 hours. How long would it take them together?", 1.2],
  ["work", "Three workers can do a job in 4, 6 and 12 days respectively. How many days will they take working together?", 2],
  ["work", "If 5 workers can build a wall in 12 days, how many days will 10 workers take?", 6],
  ["work", "If 6 machines can make 300 parts in 5 hours, how many parts can 9 machines make in 5 hours?", 450],
  ["work", "A can finish a job in 10 days and B in 15 days. How many days will they take to finish it together?", 6],
  ["work", "Maria types 60 words per minute. How long will it take her to type 1500 words?", 25],
  ["work", "It takes 8 people 6 days to paint a house. How long would it take 12 people?", 4],
  ["work", "A hose fills a tank in 20 minutes and a second hose fills it in 30 minutes. How many minutes to fill the tank with both hoses?", 12],

  // ---------------------------------------------------------------- distance, speed, time
  ["distance", "A car travels 150 miles in 3 hours. What is its average speed?", 50],
  ["distance", "How far does a train go in 4 hours at 80 km/h?", 320],
  ["distance", "How long does it take to drive 240 km at 60 km/h?", 4],
  ["distance", "Two cars leave the same town at the same time traveling in opposite directions. One travels at 50 mph and the other at 60 mph. After how many hours will they be 330 miles apart?", 3],
  ["distance", "Two trains start 400 km apart and travel toward each other at 90 km/h and 110 km/h. How long until they meet?", 2],
  ["distance", "A cyclist rides at 15 km/h for 2 hours and then at 20 km/h for 3 hours. What is the total distance?", 90],
  ["distance", "A plane flies 1200 miles in 2.5 hours. What is its speed?", 480],
  ["distance", "A boat goes 30 km upstream in 3 hours and 30 km downstream in 2 hours. What is the speed of the current?", 2.5],
  ["distance", "A runner runs 10 km in 50 minutes. What is her speed in km per hour?", 12],
  ["distance", "Jake walks at 4 mph. How far will he walk in 2.5 hours?", 10],
  ["distance", "A car leaves at 60 mph. Two hours later a second car leaves from the same place at 80 mph following the same route. How long after the second car leaves will it catch up?", 6],
  ["distance", "What is the average speed for a trip of 120 miles out at 40 mph and 120 miles back at 60 mph?", 48],
  ["distance", "A bus travels at 45 km/h. How long will it take to cover 180 km?", 4],
  ["distance", "If you drive at 55 miles per hour, how many miles do you travel in 4 hours?", 220],

  // ---------------------------------------------------------------- percentages, discounts, tax
  ["percent", "A shirt costs $40 and is on sale for 25% off. What is the sale price?", 30],
  ["percent", "What is 15% of 200?", 30],
  ["percent", "A $80 jacket is discounted by 30%. How much do you save?", 24],
  ["percent", "The price of a TV is $500 plus 8% sales tax. What is the total cost?", 540],
  ["percent", "A meal costs $60. If you leave a 15% tip, what is the total?", 69],
  ["percent", "A price increased from $50 to $65. What is the percent increase?", 30],
  ["percent", "18 is what percent of 72?", 25],
  ["percent", "After a 20% discount a book costs $24. What was the original price?", 30],
  ["percent", "A population of 2000 increases by 5%. What is the new population?", 2100],
  ["percent", "40% of what number is 60?", 150],
  ["percent", "A store marks up an item costing $25 by 40%. What is the selling price?", 35],
  ["percent", "A student scored 42 out of 50 on a test. What percent is that?", 84],
  ["percent", "A laptop originally priced at $900 is reduced by 15%. What is the new price?", 765],
  ["percent", "Sales tax is 6%. What is the tax on a $250 purchase?", 15],
  ["percent", "The price of gas went from $4 to $3. What is the percent decrease?", 25],

  // ---------------------------------------------------------------- simple and compound interest
  ["interest", "What is the simple interest on $2000 at 5% per year for 3 years?", 300],
  ["interest", "Find the simple interest on $1500 at 4% for 2 years.", 120],
  ["interest", "$1000 is invested at 6% compounded annually for 2 years. What is the final amount?", 1123.6],
  ["interest", "How much will $5000 be worth after 3 years at 4% interest compounded annually?", 5000 * 1.04 ** 3],
  ["interest", "Find the compound interest on $1000 at 10% for 2 years", 210],
  ["interest", "How much interest is earned on $800 at 3% simple interest for 5 years?", 120],
  ["interest", "A loan of $3000 at 7% simple interest for 4 years. What is the total amount to be repaid?", 3840],
  ["interest", "$2000 is invested at 5% interest compounded quarterly for 3 years. What is the balance?", 2000 * 1.0125 ** 12],
  ["interest", "At what simple interest rate will $500 earn $75 in 3 years?", 5],
  ["interest", "How many years will it take $1200 to earn $360 in simple interest at 6%?", 5],
  ["interest", "What principal will earn $240 in simple interest at 4% in 3 years?", 2000],
  ["interest", "$10000 is invested at 3% compounded monthly for 5 years. Find the final amount.", 10000 * 1.0025 ** 60],
  ["interest", "Find the amount after 2 years if $4000 is invested at 5% compounded continuously", 4000 * Math.exp(0.1)],

  // ---------------------------------------------------------------- consecutive integers
  ["consecutive", "The sum of three consecutive integers is 72. Find the integers.", { nums: [23, 24, 25] }],
  ["consecutive", "Find two consecutive even integers whose sum is 46.", { nums: [22, 24] }],
  ["consecutive", "The sum of two consecutive odd integers is 56. What are the integers?", { nums: [27, 29] }],
  ["consecutive", "Find three consecutive odd integers whose sum is 57.", { nums: [17, 19, 21] }],
  ["consecutive", "The sum of four consecutive integers is 106. What is the largest?", 28],
  ["consecutive", "The product of two consecutive positive integers is 132. Find the integers.", { nums: [11, 12] }],
  ["consecutive", "Three consecutive even numbers add up to 84. What is the smallest?", 26],
  ["consecutive", "The sum of two consecutive integers is 91. What are they?", { nums: [45, 46] }],
  ["consecutive", "The larger of two consecutive integers is 7 more than twice the smaller. Find the integers.", { nums: [-6, -5] }],
  ["consecutive", "The sum of three consecutive integers is 3 less than 4 times the smallest. Find the smallest.", 6],
  ["consecutive", "Find two consecutive odd numbers whose product is 143", { nums: [11, 13, -13, -11] }],
  ["consecutive", "Twice the smaller of two consecutive integers plus the larger is 64. Find the integers.", { nums: [21, 22] }],

  // ---------------------------------------------------------------- perimeter, area, volume
  ["geometry", "A rectangle is 12 cm long and 5 cm wide. What is its area?", 60],
  ["geometry", "The length of a rectangle is 3 more than its width. The perimeter is 26. Find the width.", 5],
  ["geometry", "A rectangular garden has a perimeter of 48 m and its length is twice its width. What is the length?", 16],
  ["geometry", "Find the area of a circle with radius 7", 49 * PI],
  ["geometry", "What is the volume of a box that is 4 by 5 by 6?", 120],
  ["geometry", "A square has a perimeter of 36. What is its area?", 81],
  ["geometry", "The area of a rectangle is 72 square feet and its width is 6 feet. What is its length?", 12],
  ["geometry", "Find the volume of a cylinder with radius 3 and height 10", 90 * PI],
  ["geometry", "A triangle has a base of 10 cm and a height of 6 cm. What is its area?", 30],
  ["geometry", "What is the circumference of a circle with a diameter of 10?", 10 * PI],
  ["geometry", "A cube has a volume of 64 cubic inches. What is the length of one edge?", 4],
  ["geometry", "The width of a rectangle is 4 less than its length. The area is 60. Find the length.", 10],
  ["geometry", "A right triangle has legs of 6 and 8. How long is the hypotenuse?", 10],
  ["geometry", "What is the perimeter of a square with side 7.5?", 30],
  ["geometry", "A circular pool has a radius of 5 m. What is its area?", 25 * PI],
  ["geometry", "Find the surface area of a cube with side 3", 54],

  // ---------------------------------------------------------------- probability of simple events
  ["probability", "What is the probability of rolling a 4 on a fair die?", 1 / 6],
  ["probability", "A bag contains 3 red marbles and 5 blue marbles. What is the probability of drawing a red marble?", 3 / 8],
  ["probability", "A bag has 4 red, 6 green and 10 blue balls. If one ball is picked at random, what is the probability it is green?", 0.3],
  ["probability", "What is the probability of getting heads when flipping a fair coin?", 0.5],
  ["probability", "What is the probability of rolling an even number on a die?", 0.5],
  ["probability", "A card is drawn from a standard deck. What is the probability that it is a king?", 1 / 13],
  ["probability", "What is the probability of rolling a number greater than 4 on a six-sided die?", 1 / 3],
  ["probability", "What is the probability of getting two heads when flipping two coins?", 0.25],
  ["probability", "A spinner has 8 equal sections numbered 1 to 8. What is the probability of landing on a number less than 3?", 0.25],
  ["probability", "A box contains 5 defective and 15 good bulbs. What is the probability that a randomly chosen bulb is not defective?", 0.75],
  ["probability", "What is the probability of rolling a sum of 7 with two dice?", 1 / 6],
  ["probability", "A jar has 7 red and 3 yellow candies. Two candies are drawn without replacement. What is the probability both are red?", 7 / 15],
  ["probability", "The probability of rain tomorrow is 0.3. What is the probability that it does not rain?", 0.7],
  ["probability", "What is the probability of drawing a heart from a deck of cards?", 0.25],
  ["probability", "A number is chosen at random from 1 to 20. What is the probability that it is a multiple of 5?", 0.2],

  // ---------------------------------------------------------------- unit rates
  ["unit-rate", "If 3 apples cost $1.50, how much do 10 apples cost?", 5],
  ["unit-rate", "A 12-ounce box of cereal costs $3.60. What is the price per ounce?", 0.3],
  ["unit-rate", "A car uses 8 gallons of gas to travel 240 miles. How many miles per gallon does it get?", 30],
  ["unit-rate", "5 pounds of apples cost $7.50. What is the price per pound?", 1.5],
  ["unit-rate", "A worker earns $150 for 8 hours of work. How much does she earn per hour?", 18.75],
  ["unit-rate", "If a printer prints 45 pages in 3 minutes, how many pages does it print in 10 minutes?", 150],
  ["unit-rate", "A car travels 300 miles on 12 gallons of gas. How far can it travel on 20 gallons?", 500],
  ["unit-rate", "If 4 notebooks cost $10, what is the cost of 7 notebooks?", 17.5],
  ["unit-rate", "A recipe uses 2 cups of flour for 12 cookies. How many cups of flour are needed for 30 cookies?", 5],
  ["unit-rate", "Tom earns $12 per hour. How much does he earn in 35 hours?", 420],
  ["unit-rate", "A faucet drips 3 liters in 4 hours. How many liters does it drip in 24 hours?", 18],
  ["unit-rate", "If 6 pens cost $9, how much does one pen cost?", 1.5],

  // ---------------------------------------------------------------- ratios and proportions
  ["ratio", "The ratio of boys to girls in a class is 3:5. If there are 40 students, how many girls are there?", 25],
  ["ratio", "Divide 120 in the ratio 2:3", { nums: [48, 72] }],
  ["ratio", "Solve the proportion 3/4 = x/20", 15],
  ["ratio", "The ratio of cats to dogs is 2:3. There are 12 cats. How many dogs are there?", 18],
  ["ratio", "A map scale is 1 cm to 5 km. Two towns are 7 cm apart on the map. What is the actual distance?", 35],
  ["ratio", "The ratio of red to blue marbles is 4:7. If there are 28 blue marbles, how many red marbles are there?", 16],
  ["ratio", "Share $90 between Ann and Bob in the ratio 4:5. How much does Bob get?", 50],
  ["ratio", "A recipe calls for flour and sugar in the ratio 5:2. If you use 10 cups of flour, how much sugar do you need?", 4],
  ["ratio", "The angles of a triangle are in the ratio 1:2:3. Find the largest angle.", 90],
  ["ratio", "Two numbers are in the ratio 3:4 and their sum is 63. Find the numbers.", { nums: [27, 36] }],
  ["ratio", "If 5 pounds of apples cost $8, how much do 15 pounds cost?", 24],
  ["ratio", "The ratio of teachers to students is 1:25. If there are 500 students, how many teachers are there?", 20],

  // ---------------------------------------------------------------- "a number" sentences
  ["number", "A number plus twice the number is 21. Find the number.", 7],
  ["number", "Five more than three times a number is 29. What is the number?", 8],
  ["number", "Twice a number decreased by 7 is 15.", 11],
  ["number", "The sum of a number and 12 is 30.", 18],
  ["number", "A number divided by 4 is 9. What is the number?", 36],
  ["number", "Seven less than a number is 20.", 27],
  ["number", "When 6 is added to four times a number, the result is 50. Find the number.", 11],
  ["number", "The difference between a number and 9 is 14.", 23],
  ["number", "Half of a number plus 5 is 12.", 14],
  ["number", "Three times a number minus 4 equals twice the number plus 6. Find the number.", 10],
  ["number", "The sum of two numbers is 50. One number is 8 more than the other. Find the numbers.", { nums: [21, 29] }],
  ["number", "One number is 3 times another. Their sum is 48. Find the numbers.", { nums: [12, 36] }],
  ["number", "A number squared is 81. What is the number?", { nums: [9, -9] }],
  ["number", "The product of a number and 6 is 72.", 12],
  ["number", "If 5 is subtracted from a number, the result is 18. Find the number.", 23],
  ["number", "Twice the sum of a number and 3 is 20. Find the number.", 7],
  ["number", "The quotient of a number and 3 is 8.", 24],

  // ---------------------------------------------------------------- systems (tickets, coins, heads and legs)
  ["system", "Adult tickets cost $8 and child tickets cost $5. 200 tickets were sold for a total of $1300. How many adult tickets were sold?", 100],
  ["system", "A theater sold 300 tickets. Adult tickets cost $10 and student tickets cost $6. Total sales were $2400. How many student tickets were sold?", 150],
  ["system", "Jenny has 20 coins in dimes and quarters worth $3.20. How many quarters does she have?", 8],
  ["system", "A farmer has chickens and cows. There are 30 heads and 74 legs. How many cows are there?", 7],
  ["system", "The sum of two numbers is 30 and their difference is 6. Find the numbers.", { nums: [18, 12] }],
  ["system", "2 pencils and 3 pens cost $13. 4 pencils and 1 pen cost $11. How much does a pen cost?", 3],
  ["system", "A school sold 150 tickets. Student tickets were $3 and adult tickets were $5. They made $590. How many of each were sold?", { nums: [80, 70] }],
  ["system", "You have 15 bills in $5 and $10 bills totaling $110. How many $10 bills do you have?", 7],
  ["system", "Solve the system: x + y = 10 and x - y = 2", { nums: [6, 4] }],
  ["system", "A boat travels 24 miles downstream in 2 hours and 24 miles upstream in 3 hours. Find the speed of the boat in still water.", 10],
  ["system", "The sum of two numbers is 25 and their product is 144. Find the numbers.", { nums: [16, 9] }],
  ["system", "A total of 500 tickets were sold. Adult tickets cost $12 and children's tickets cost $7. The total revenue was $4750. How many children's tickets were sold?", 250],
  ["system", "In a parking lot there are cars and motorcycles. There are 40 vehicles and 130 wheels. How many motorcycles are there?", 15],

  // ---------------------------------------------------------------- angles
  ["angles", "Two angles are complementary. One is 20 degrees more than the other. Find the smaller angle.", 35],
  ["angles", "Two angles are supplementary and one is twice the other. Find the larger angle.", 120],
  ["angles", "Find the complement of a 35 degree angle.", 55],
  ["angles", "Find the supplement of 110 degrees.", 70],
  ["angles", "Two angles of a triangle are 50 and 60 degrees. What is the third angle?", 70],
  ["angles", "In a triangle, the second angle is twice the first and the third angle is 3 times the first. Find the first angle.", 30],
  ["angles", "What is each interior angle of a regular hexagon?", 120],
  ["angles", "What is the sum of the interior angles of a pentagon?", 540],
  ["angles", "One angle of an isosceles triangle is 40 degrees and the other two are equal. What is each of the equal angles?", 70],
  ["angles", "The measure of an angle is 4 times its complement. Find the angle.", 72],
  ["angles", "An angle is 30 degrees less than its supplement. Find the angle.", 75],
  ["angles", "In a right triangle one acute angle is 25 degrees. What is the other acute angle?", 65],
  ["angles", "The angles of a quadrilateral are x, 2x, 3x and 4x. Find x.", 36],
];
