// Held-out coverage cases: different numbers and phrasings from quelvra-coverage-cases.mjs, written
// after the engine work to check that the new patterns generalise. Expected values checked by hand.
const PI = Math.PI;
export const CASES = [
  ["prob", "what is the probability of rolling a 3 on a fair die", 1 / 6],
  ["prob", "probability of getting a sum of 9 when rolling two dice", 4 / 36],
  ["prob", "probability of exactly 2 heads in 4 coin tosses", 6 / 16],
  ["prob", "probability of at least one head in 5 coin flips", 31 / 32],
  ["prob", "probability of drawing a king from a standard deck", 1 / 13],
  ["prob", "probability of drawing a red card or a queen", 28 / 52],
  ["prob", "binompdf(8, 0.25, 3)", 56 * 0.25 ** 3 * 0.75 ** 5],
  ["prob", "normalcdf(-1, 1)", 0.6826894921],
  ["prob", "P(Z < 2)", 0.9772498681],
  ["prob", "P(Z > 1)", 0.1586552539],
  ["stats", "mean of 12, 15, 18, 21", 16.5],
  ["stats", "median of 7, 2, 9, 4, 5", 5],
  ["stats", "sample variance of 2, 4, 6", 4],
  ["stats", "population variance of 2, 4, 6", 8 / 3],
  ["stats", "standard deviation of 10, 12, 14", 2],
  ["stats", "interquartile range of 1, 2, 3, 4, 5, 6, 7, 8", 4],
  ["stats", "z-score of 60 with mean 50 and standard deviation 5", 2],
  ["stats", "invnorm(0.975)", 1.959963985],
  ["combin", "8 choose 3", 56],
  ["combin", "C(12, 4)", 495],
  ["combin", "P(7, 3)", 210],
  ["combin", "how many ways can 6 people be arranged in a row", 720],
  ["combin", "number of arrangements of the letters in banana", 60],
  ["combin", "how many ways to choose 2 from 9", 36],
  ["combin", "number of diagonals of a decagon", 35],
  ["combin", "derangements of 5", 44],
  ["complex", "(2 + 3i)(1 - i)", { re: /5 \+ i|5 \+ 1i|i \+ 5/ }],
  ["complex", "modulus of 5 - 12i", 13],
  ["complex", "conjugate of 4 + 7i", { re: /4 - 7i|-7i \+ 4/ }],
  ["complex", "convert -1 + i to polar form", { re: /sqrt\(2\).*3pi\/4|3pi\/4.*sqrt\(2\)/ }],
  ["complex", "polar form of -3", { re: /3.*pi/ }],
  ["complex", "polar(1 - sqrt(3)i)", { re: /-pi\/3/ }],
  ["series", "12th term of the arithmetic sequence 2, 5, 8, ...", 35],
  ["series", "5th term of the geometric sequence 3, 6, 12, ...", 48],
  ["series", "sum of the first 10 terms of the geometric series 1, 3, 9, ...", 29524],
  ["series", "sum of the first 15 terms of the arithmetic series 4, 7, 10, ...", 375],
  ["series", "sum of the first 50 positive integers", 1275],
  ["geometry", "area of a circle with radius 5", 25 * PI],
  ["geometry", "volume of a sphere of radius 2", 32 * PI / 3],
  ["geometry", "hypotenuse of a right triangle with legs 8 and 15", 17],
  ["geometry", "area of a triangle with sides 5, 5 and 6", 12],
  ["geometry", "volume of a cylinder with radius 3 and height 4", 36 * PI],
  ["geometry", "sum of interior angles of a hexagon", 720],
  ["geometry", "distance from (0, 0) to the line 3x + 4y - 10 = 0", 2],
  ["trig", "solve 2sin(x) = 1 for 0 <= x < 2pi", { re: /pi\/6.*5pi\/6/ }],
  ["trig", "solve tan(x) = 1 on [0, 2pi)", { re: /pi\/4.*5pi\/4/ }],
  ["trig", "convert 150 degrees to radians", 5 * PI / 6],
  ["logs", "log(1000)", 3],
  ["logs", "solve 3^x = 81", 4],
  ["logs", "condense log(2) + log(5)", { re: /log\(10\)|^1$/ }],
  ["poly", "divide x^3 - 1 by x - 1", { re: /x\^2 \+ x \+ 1/ }],
  ["poly", "remainder when x^3 + 2x + 5 is divided by x - 2", 17],
  ["poly", "discriminant of 2x^2 + 3x - 5", 49],
  ["poly", "sum of the roots of x^2 - 7x + 10", 7],
  ["matrix", "det([[2, 1], [5, 3]])", 1],
  ["matrix", "[[1, 2], [3, 4]] * [[0, 1], [1, 0]]", { re: /\[\[2, 1\], \[4, 3\]\]/ }],
  ["numtheory", "gcd(84, 36)", 12],
  ["numtheory", "lcm(6, 15)", 30],
  ["numtheory", "inverse of 3 mod 11", 4],
  ["numtheory", "convert 255 to base 2", { re: /11111111/ }],
  ["numtheory", "phi(36)", 12],
  ["numtheory", "10th prime", 29],
  ["logic", "truth table for p and not q", { re: /T/ }],
  ["logic", "is p or not p a tautology", { re: /tautology/i }],
  ["calculus", "derivative of x^3 sin(x)", { re: /3x\^2\*?sin\(x\)|x\^3\*?cos\(x\)/ }],
  ["calculus", "integrate x e^x", { re: /x\*?e\^x - e\^x|e\^x\*?x - e\^x|e\^x\*?\(x - 1\)/ }],
  ["calculus", "limit of sin(3x)/x as x approaches 0", 3],
  ["calculus", "slope of the tangent to y = x^2 at x = 3", 6],
  ["arith", "round 3.14159 to 2 decimal places", 3.14],
  ["arith", "0.125 as a fraction", 1 / 8],
  ["word", "find two consecutive integers whose product is 72", { re: /8.*9|-9.*-8/ }],
  ["word", "the sum of a number and 7 is 20. find the number", 13],
  // should refuse: not math, or unsupported
  ["refuse", "hello there", { refuse: true }],
  ["refuse", "what is love", { refuse: true }],
  ["refuse", "x form 3", { refuse: true }],
];
