// Coverage probe cases (see tools/coverage.mjs). Expected values checked by hand / sympy.
const PI = Math.PI;
export const CASES = [
  // ---------------- probability
  ["prob", "probability of rolling a 6 on a die", 1 / 6],
  ["prob", "probability of rolling a sum of 7 with two dice", 1 / 6],
  ["prob", "probability of getting exactly 3 heads in 5 coin flips", 10 / 32],
  ["prob", "probability of at least one head in 3 coin tosses", 7 / 8],
  ["prob", "probability of drawing an ace from a deck of cards", 1 / 13],
  ["prob", "probability of drawing 2 aces from a deck without replacement", 1 / 221],
  ["prob", "binomial probability n=10 p=0.5 k=3", 120 / 1024],
  ["prob", "binompdf(10, 0.3, 2)", 0.2334744405],
  ["prob", "binomcdf(10, 0.5, 3)", 176 / 1024],
  ["prob", "expected value of a fair die", 3.5],
  ["prob", "P(A and B) if P(A)=0.3 and P(B)=0.5 independent", 0.15],
  ["prob", "P(A|B) = P(A and B)/P(B) with P(A and B)=0.2, P(B)=0.5", 0.4],
  ["prob", "probability of rolling doubles with two dice", 1 / 6],
  ["prob", "poissonpdf(3, 2)", 0.2240418077],
  ["prob", "geometric probability first success on trial 3 with p = 0.2", 0.128],
  ["prob", "probability that a card is a heart or a king", 16 / 52],
  // ---------------- statistics
  ["stats", "mean of 2, 4, 6, 8, 10", 6],
  ["stats", "median of 3, 1, 4, 1, 5, 9, 2, 6", 3.5],
  ["stats", "mode of 1, 2, 2, 3, 3, 3, 4", 3],
  ["stats", "standard deviation of 2, 4, 4, 4, 5, 5, 7, 9", Math.sqrt(32 / 7)],
  ["stats", "population standard deviation of 2, 4, 4, 4, 5, 5, 7, 9", 2],
  ["stats", "variance of 1, 2, 3, 4, 5", 2.5],
  ["stats", "range of the data 3, 8, 1, 9, 4", 8],
  ["stats", "first quartile of 1, 2, 3, 4, 5, 6, 7, 8", 2.5],
  ["stats", "z-score of 85 with mean 70 and standard deviation 10", 1.5],
  ["stats", "normalcdf(-1, 1)", 0.6826894921],
  ["stats", "normalcdf(-inf, 1.96)", 0.9750021049],
  ["stats", "P(Z < 1.5)", 0.9331927987],
  ["stats", "invnorm(0.975)", 1.959963985],
  ["stats", "mean(1, 2, 3, 4, 100)", 22],
  ["stats", "sum of 1, 2, 3, 4, 5", 15],
  ["stats", "weighted mean of 80, 90 with weights 1, 3", 87.5],
  ["stats", "correlation of x = [1,2,3,4,5] and y = [2,4,5,4,5]", 0.7745966692],
  ["stats", "linear regression of x = [1,2,3,4] and y = [2,4,6,8]", { re: /2\s*x|2x/ }],
  // ---------------- combinatorics
  ["combin", "10 choose 3", 120],
  ["combin", "C(10, 3)", 120],
  ["combin", "nCr(52, 5)", 2598960],
  ["combin", "P(10, 3)", 720],
  ["combin", "nPr(8, 2)", 56],
  ["combin", "binomial(6, 2)", 15],
  ["combin", "5!", 120],
  ["combin", "10!/(3!*7!)", 120],
  ["combin", "number of ways to arrange the letters of MISSISSIPPI", 34650],
  ["combin", "number of permutations of 5 objects", 120],
  ["combin", "how many ways to choose 3 people from 8", 56],
  ["combin", "number of ways to put 10 identical balls into 4 boxes", 286],
  ["combin", "number of subsets of a set with 5 elements", 32],
  ["combin", "number of diagonals of a decagon", 35],
  ["combin", "number of 4 digit PINs", 10000],
  ["combin", "number of derangements of 5", 44],
  ["combin", "catalan(5)", 42],
  ["combin", "fibonacci(20)", 6765],
  // ---------------- complex numbers
  ["complex", "(3 + 4i)(1 - 2i)", { re: /11 - 2i|-2i \+ 11/ }],
  ["complex", "(1+i)/(1-i)", { re: /^i$|= i$/ }],
  ["complex", "abs(3 + 4i)", 5],
  ["complex", "modulus of 3 + 4i", 5],
  ["complex", "arg(1 + i)", PI / 4],
  ["complex", "argument of -1 + i", 3 * PI / 4],
  ["complex", "conjugate of 2 - 5i", { re: /2 \+ 5i|5i \+ 2/ }],
  ["complex", "i^2023", { re: /^-i$|= -i$/ }],
  ["complex", "(1+i)^8", 16],
  ["complex", "sqrt(-16)", { re: /4i/ }],
  ["complex", "e^(i*pi)", -1],
  ["complex", "solve z^2 + 4 = 0 over complex", { re: /2i/ }],
  ["complex", "solve z^3 = 1 over complex", { re: /sqrt\(3\)/ }],
  ["complex", "real part of (2+3i)^2", -5],
  ["complex", "imaginary part of (2+3i)^2", 12],
  ["complex", "convert 1 + i to polar form", { re: /sqrt\(2\)|pi\/4/ }],
  ["complex", "roots of unity of order 4", { re: /i/ }],
  // ---------------- ODEs
  ["ode", "y' = 2y", { re: /e\^\(2x\)|e\^\(2 ?x\)/ }],
  ["ode", "dy/dx = x*y", { re: /e\^/ }],
  ["ode", "y'' + y = 0", { re: /sin|cos/ }],
  ["ode", "y'' - 3y' + 2y = 0", { re: /e\^/ }],
  ["ode", "y' + y = x", { re: /x - 1|e\^\(-x\)/ }],
  ["ode", "y' = y, y(0) = 1", { expr: "e^x" }],
  ["ode", "y'' + 4y = 0, y(0) = 0, y'(0) = 2", { expr: "sin(2x)" }],
  ["ode", "dy/dx = 3x^2, y(0) = 1", { expr: "x^3 + 1" }],
  ["ode", "y'' - 2y' + y = 0", { re: /x/ }],
  ["ode", "solve the differential equation y' = -2xy", { re: /e\^/ }],
  ["ode", "y' = y^2", { re: /1\/|\/\(/ }],
  ["ode", "y'' + y' - 6y = 0", { re: /e\^/ }],
  // ---------------- sequences and series
  ["series", "sum of the first 100 positive integers", 5050],
  ["series", "sum(k, k, 1, 100)", 5050],
  ["series", "sum(k^2, k, 1, 10)", 385],
  ["series", "sum(1/2^k, k, 0, oo)", 2],
  ["series", "sum(1/k^2, k, 1, oo)", PI * PI / 6],
  ["series", "sum of the geometric series 3 + 6 + 12 + ... 10 terms", 3069],
  ["series", "10th term of the arithmetic sequence 3, 7, 11, ...", 39],
  ["series", "nth term of the arithmetic sequence 2, 5, 8", { expr: "3n - 1", v: "n" }],
  ["series", "sum of the infinite geometric series with a = 4 and r = 1/2", 8],
  ["series", "does sum 1/n converge", { re: /diverg/i }],
  ["series", "sum(1/n, n, 1, oo)", { re: /diverg|oo|infin/i }],
  ["series", "sum((-1)^(n+1)/n, n, 1, oo)", Math.LN2],
  ["series", "taylor series of e^x at 0 order 4", { expr: "1 + x + x^2/2 + x^3/6 + x^4/24" }],
  ["series", "maclaurin series of sin(x) up to x^5", { expr: "x - x^3/6 + x^5/120" }],
  ["series", "sum(k^3, k, 1, n)", { expr: "n^2(n+1)^2/4", v: "n" }],
  ["series", "limit of (1 + 1/n)^n as n -> oo", Math.E],
  ["series", "sum(1/(k(k+1)), k, 1, oo)", 1],
  // ---------------- geometry
  ["geometry", "area of a circle with radius 5", 25 * PI],
  ["geometry", "circumference of a circle with radius 3", 6 * PI],
  ["geometry", "area of a triangle with base 10 and height 6", 30],
  ["geometry", "area of a triangle with sides 3, 4, 5", 6],
  ["geometry", "volume of a sphere with radius 3", 36 * PI],
  ["geometry", "surface area of a sphere with radius 2", 16 * PI],
  ["geometry", "volume of a cylinder with radius 2 and height 5", 20 * PI],
  ["geometry", "volume of a cone with radius 3 and height 4", 12 * PI],
  ["geometry", "hypotenuse of a right triangle with legs 5 and 12", 13],
  ["geometry", "a^2 + b^2 = c^2, a = 6, b = 8", { re: /10/ }],
  ["geometry", "distance between (1, 2) and (4, 6)", 5],
  ["geometry", "midpoint of (2, 4) and (6, 8)", { re: /4, 6/ }],
  ["geometry", "slope of the line through (1, 2) and (3, 8)", 3],
  ["geometry", "equation of the line through (1, 2) and (3, 8)", { re: /3x - 1/ }],
  ["geometry", "area of a rectangle 4 by 7", 28],
  ["geometry", "area of a trapezoid with bases 3 and 5 and height 4", 16],
  ["geometry", "sum of interior angles of a hexagon", 720],
  ["geometry", "law of cosines a = 7, b = 8, C = 60 degrees find c", Math.sqrt(57)],
  ["geometry", "distance from the point (1, 2) to the line 3x + 4y - 5 = 0", 6 / 5],
  ["geometry", "center and radius of x^2 + y^2 - 4x + 6y - 3 = 0", { re: /4|\(2, -3\)/ }],
  ["geometry", "volume of a cube with side 3", 27],
  ["geometry", "diagonal of a square with side 4", 4 * Math.SQRT2],
  // ---------------- trig
  ["trig", "sin(pi/6)", 0.5],
  ["trig", "cos(pi/3)", 0.5],
  ["trig", "tan(pi/4)", 1],
  ["trig", "sin(30 degrees)", 0.5],
  ["trig", "cos(45°)", Math.SQRT1_2],
  ["trig", "sin(75°)", Math.sin(75 * PI / 180)],
  ["trig", "asin(1/2)", PI / 6],
  ["trig", "arctan(1)", PI / 4],
  ["trig", "acos(-1/2)", 2 * PI / 3],
  ["trig", "solve sin(x) = 1/2", { re: /pi\/6|5pi\/6/ }],
  ["trig", "solve 2cos(x) - 1 = 0 for 0 <= x < 2pi", { roots: [PI / 3, 5 * PI / 3] }],
  ["trig", "solve tan(x) = 1", { re: /pi\/4/ }],
  ["trig", "simplify sin(x)^2 + cos(x)^2", 1],
  ["trig", "prove sin(2x) = 2sin(x)cos(x)", { re: /identity|true/i }],
  ["trig", "simplify (1 - cos(2x))/2", { expr: "sin(x)^2" }],
  ["trig", "convert 180 degrees to radians", PI],
  ["trig", "convert pi/3 radians to degrees", 60],
  ["trig", "sec(pi/3)", 2],
  ["trig", "cos(2pi/3) + sin(pi/6)", 0],
  ["trig", "expand sin(a + b)", { re: /sin\(a\)\*?cos\(b\)|cos\(b\)\*?sin\(a\)/ }],
  // ---------------- logs and exponentials
  ["logs", "log(1000)", 3],
  ["logs", "log base 2 of 32", 5],
  ["logs", "ln(e^5)", 5],
  ["logs", "solve 2^x = 16", { roots: [4] }],
  ["logs", "solve e^x = 5", { roots: [Math.log(5)] }],
  ["logs", "solve log(x) = 2", { roots: [100] }],
  ["logs", "solve ln(x) + ln(x - 1) = ln(6)", { roots: [3] }],
  ["logs", "solve 3^(2x) = 27", { roots: [1.5] }],
  ["logs", "solve 5^x = 2^(x+1)", { roots: [Math.log(2) / Math.log(2.5)] }],
  ["logs", "log_3(81)", 4],
  ["logs", "expand log(x^2 y)", { re: /2log\(\|?x\|?\)/ }],
  ["logs", "condense 2ln(x) + ln(y)", { re: /ln\(x\^2y\)|ln\(x\^2 ?\*?y\)|ln\(y ?x\^2\)/ }],
  ["logs", "compound interest 1000 at 5% for 10 years", 1000 * 1.05 ** 10],
  ["logs", "half-life: 100 grams, half life 5 years, amount after 15 years", 12.5],
  ["logs", "solve 2^x = 3", { roots: [Math.log(3) / Math.log(2)] }],
  // ---------------- inequalities
  ["ineq", "solve x^2 - 5x + 6 > 0", { re: /x < 2.*3 < x|x > 3/ }],
  ["ineq", "solve |x - 3| < 5", { re: /-2 < x < 8/ }],
  ["ineq", "solve (x - 1)/(x + 2) >= 0", { re: /x < -2.*1 <= x/ }],
  ["ineq", "solve 2x + 3 <= 11", { re: /x <= 4/ }],
  ["ineq", "solve |2x + 1| >= 3", { re: /x <= -2.*1 <= x/ }],
  ["ineq", "solve x^3 - x < 0", { re: /x < -1.*0 < x < 1/ }],
  ["ineq", "solve -3 < 2x - 1 < 5", { re: /-1 < x < 3/ }],
  ["ineq", "solve x^2 < 4", { re: /-2 < x < 2/ }],
  ["ineq", "solve 1/x > 2", { re: /0 < x < 1\/2/ }],
  ["ineq", "solve e^x > 2", { re: /ln\(2\) < x/ }],
  // ---------------- polynomials
  ["poly", "divide x^3 - 2x^2 + 4 by x - 3", { re: /x\^2 \+ x \+ 3|13/ }],
  ["poly", "remainder when x^3 + 2x - 5 is divided by x - 2", 7],
  ["poly", "factor x^3 - 6x^2 + 11x - 6", { re: /\(x - 1\)\(x - 2\)\(x - 3\)/ }],
  ["poly", "factor x^4 - 16", { re: /x\^2 \+ 4/ }],
  ["poly", "roots of x^3 - 3x + 2", { roots: [-2, 1] }],
  ["poly", "solve x^4 - 5x^2 + 4 = 0", { roots: [-2, -1, 1, 2] }],
  ["poly", "solve x^3 = 8", { roots: [2] }],
  ["poly", "expand (x + 2)^5", { expr: "(x+2)^5" }],
  ["poly", "coefficient of x^3 in (1 + x)^7", 35],
  ["poly", "sum of the roots of x^2 - 7x + 10", 7],
  ["poly", "gcd(x^2 - 1, x^2 + 2x + 1)", { expr: "x + 1" }],
  ["poly", "discriminant of 2x^2 + 3x - 5", 49],
  ["poly", "vertex of y = x^2 - 4x + 1", { re: /2, -3/ }],
  ["poly", "solve x^2 + x + 1 = 0", { none: true }],
  ["poly", "solve 2x^2 - 3x - 2 = 0", { roots: [-0.5, 2] }],
  ["poly", "solve x^5 - x = 0", { roots: [-1, 0, 1] }],
  // ---------------- matrices
  ["matrix", "det([[1,2],[3,4]])", -2],
  ["matrix", "inverse of [[1,2],[3,4]]", { re: /-2, 1\]|3\/2/ }],
  ["matrix", "eigenvalues of [[2,0],[0,3]]", { re: /2.*3|3.*2/ }],
  ["matrix", "eigenvalues of [[4,1],[2,3]]", { re: /2.*5|5.*2/ }],
  ["matrix", "[[1,2],[3,4]] * [[5,6],[7,8]]", { re: /19, 22/ }],
  ["matrix", "[[1,1],[1,0]]^10", { re: /89, 55/ }],
  ["matrix", "transpose of [[1,2,3],[4,5,6]]", { re: /\[1, 4\]/ }],
  ["matrix", "rank of [[1,2],[2,4]]", 1],
  ["matrix", "solve x + y = 3, x - y = 1", { re: /x = 2.*y = 1/ }],
  ["matrix", "solve 2x + y - z = 8, -3x - y + 2z = -11, -2x + y + 2z = -3", { re: /x = 2.*y = 3.*z = -1/ }],
  ["matrix", "trace of [[1,2],[3,4]]", 5],
  ["matrix", "rref([[1,2,3],[4,5,6]])", { re: /\[1, 0, -1\]/ }],
  ["matrix", "determinant of [[2,0,1],[1,3,2],[1,1,1]]", 0],
  // ---------------- number theory
  ["numtheory", "gcd(48, 180)", 12],
  ["numtheory", "lcm(12, 18)", 36],
  ["numtheory", "is 97 prime", { re: /prime|true/i }],
  ["numtheory", "prime factorization of 360", { re: /2\^3/ }],
  ["numtheory", "inverse of 3 mod 11", 4],
  ["numtheory", "modular inverse of 17 mod 3120", 2753],
  ["numtheory", "phi(36)", 12],
  ["numtheory", "2^100 mod 7", 2],
  ["numtheory", "convert 255 to binary", { re: /11111111/ }],
  ["numtheory", "convert 1010 from binary to decimal", 10],
  ["numtheory", "255 in hexadecimal", { re: /ff/i }],
  ["numtheory", "number of divisors of 360", 24],
  ["numtheory", "sum of divisors of 28", 56],
  ["numtheory", "17 mod 5", 2],
  ["numtheory", "remainder of 2^50 divided by 13", 4],
  ["numtheory", "last digit of 7^2023", 3],
  ["numtheory", "10th prime", 29],
  ["numtheory", "solve 3x ≡ 4 (mod 7)", { re: /7k \+ 6/ }],
  // ---------------- logic and sets
  ["logic", "truth table of p and q", { re: /T|F|true|false/i }],
  ["logic", "{1, 2, 3} union {3, 4}", { re: /1, 2, 3, 4/ }],
  ["logic", "{1, 2, 3} intersect {2, 3, 4}", { re: /2, 3/ }],
  ["logic", "number of elements in the power set of {a, b, c}", 8],
  ["logic", "is p or not p a tautology", { re: /tautology|true/i }],
  ["logic", "simplify not (p and q)", { re: /not p or not q|¬p ∨ ¬q/i }],
  // ---------------- calculus in plain English
  ["calculus", "derivative of x^3 sin(x)", { expr: "3x^2 sin(x) + x^3 cos(x)" }],
  ["calculus", "differentiate e^(2x) with respect to x", { expr: "2e^(2x)" }],
  ["calculus", "second derivative of x^4", { expr: "12x^2" }],
  ["calculus", "integrate x^2 from 0 to 3", 9],
  ["calculus", "integral of 1/x", { anti: "ln(abs(x))" }],
  ["calculus", "antiderivative of cos(x)", { anti: "sin(x)" }],
  ["calculus", "integral of x e^x dx", { anti: "(x - 1)e^x" }],
  ["calculus", "integral from 0 to pi of sin(x)", 2],
  ["calculus", "integral from 0 to infinity of e^(-x)", 1],
  ["calculus", "limit of sin(x)/x as x approaches 0", 1],
  ["calculus", "limit of (x^2 - 1)/(x - 1) as x -> 1", 2],
  ["calculus", "limit as x goes to infinity of (3x^2 + 1)/(x^2 - 2)", 3],
  ["calculus", "find the critical points of x^3 - 3x", { re: /-1.*1|1.*-1/ }],
  ["calculus", "maximum of -x^2 + 4x", 4],
  ["calculus", "slope of the tangent to y = x^2 at x = 3", 6],
  ["calculus", "partial derivative of x^2 y with respect to y", { expr: "x^2" }],
  ["calculus", "area under y = x^2 from 0 to 2", 8 / 3],
  ["calculus", "d/dx ln(x^2 + 1)", { expr: "2x/(x^2+1)" }],
  ["calculus", "integrate 1/(1 + x^2) dx", { anti: "atan(x)" }],
  ["calculus", "integral of sqrt(x) from 1 to 4", 14 / 3],
  ["calculus", "gradient of x^2 + y^2", { re: /2x.*2y/ }],
  ["calculus", "double integral of x*y over 0<=x<=1, 0<=y<=2", 1],
  // ---------------- arithmetic and algebra basics
  ["algebra", "solve 2x + 3 = 11", { roots: [4] }],
  ["algebra", "solve x^2 - 5x + 6 = 0", { roots: [2, 3] }],
  ["algebra", "simplify (x^2 - 9)/(x - 3)", { expr: "x + 3" }],
  ["algebra", "expand (a + b)^3", { re: /a\^3/ }],
  ["algebra", "15% of 80", 12],
  ["algebra", "what is 3/4 + 5/6", 19 / 12],
  ["algebra", "sqrt(50)", 5 * Math.SQRT2],
  ["algebra", "solve for y: 3x + 2y = 6", { expr: "3 - 3x/2" }],
  ["algebra", "solve sqrt(x + 3) = x - 3", { roots: [6] }],
  ["algebra", "solve |x - 2| = 5", { roots: [-3, 7] }],
  ["algebra", "solve x/(x-1) = 2", { roots: [2] }],
  ["algebra", "2^10", 1024],
  ["algebra", "27^(2/3)", 9],
  ["algebra", "round 3.14159 to 2 decimal places", 3.14],
  ["algebra", "percent increase from 50 to 65", 30],
  ["algebra", "floor(3.7) + ceil(2.1)", 6],
  ["algebra", "0.333... as a fraction", 1 / 3],
  ["algebra", "0.125 as a fraction", 0.125],
  ["algebra", "solve x^2 = 2x + 8", { roots: [-2, 4] }],
  ["algebra", "solve 1/x + 1/(x+1) = 1/2", { roots: [1 - Math.sqrt(... [0]) || 0] }],
  // ---------------- word problems
  ["word", "a train travels 120 km in 2 hours. what is its speed", 60],
  ["word", "if 3 apples cost 6 dollars how much do 7 apples cost", 14],
  ["word", "the sum of two numbers is 20 and their difference is 4. find the numbers", { re: /12.*8|8.*12/ }],
  ["word", "a rectangle has perimeter 30 and length 9. find its width", 6],
  ["word", "john is twice as old as mary. in 5 years the sum of their ages will be 40. how old is mary", 10],
  ["word", "what number increased by 7 is 19", 12],
  ["word", "simple interest on 500 at 4% for 3 years", 60],
  ["word", "a car depreciates 10% per year from 20000. value after 3 years", 14580],
  ["word", "find two consecutive integers whose product is 56", { re: /7.*8|-8.*-7/ }],
  ["word", "the area of a square is 49. find its side", 7],
];
// the one malformed placeholder above is replaced here: 1/x + 1/(x+1) = 1/2 -> x^2 - 3x - 2 = 0
CASES.forEach((c) => { if (c[1] === "solve 1/x + 1/(x+1) = 1/2") c[2] = { roots: [(3 - Math.sqrt(17)) / 2, (3 + Math.sqrt(17)) / 2] }; });
