// Everyday phrasings (plain student wording) that Quelvra must understand AND verify: each one is
// an answer, not a refusal (test/everyday.test.js). Expected values checked by hand.
const PI = Math.PI;
export const CASES = [
  ["arith", "whats 15 percent of 80", 12], ["arith", "what is 3/4 plus 2/3", 17 / 12], ["arith", "how much is 7 times 8", 56],
  ["arith", "percent change from 50 to 75", 50], ["arith", "what percent of 80 is 20", 25], ["arith", "20 is what percent of 80", 25],
  ["arith", "increase 80 by 15%", 92], ["arith", "decrease 80 by 15 percent", 68], ["arith", "convert 0.75 to a fraction", { re: /3\/4|3 \/ 4/ }],
  ["arith", "write 5/8 as a decimal", 0.625], ["arith", "3/8 as a percent", 37.5], ["arith", "simplify 18/24", { re: /3\/4|3 \/ 4/ }],
  ["arith", "what's the square root of 50", Math.sqrt(50)], ["arith", "simplify sqrt(50)", { re: /5.*sqrt\(2\)|5√2/ }], ["arith", "cube root of 64", 4],
  ["arith", "what is 2 to the power of 10", 1024], ["arith", "log base 2 of 8", 3], ["arith", "natural log of e squared", 2],
  ["arith", "round 3.14159 to 2 decimal places", 3.14], ["arith", "reciprocal of 4", 0.25], ["arith", "average of 4, 8 and 12", 8],
  ["arith", "lcm of 4 and 6", 12], ["arith", "greatest common factor of 24 and 36", 12], ["arith", "is 91 prime", { re: /91 is not prime: 91 = 7\*13/ }],
  ["arith", "prime factorization of 360", { re: /2\^3.*3\^2.*5/ }], ["arith", "what is 12 factorial", 479001600], ["arith", "10 choose 3", 120],
  ["arith", "absolute value of -7", 7], ["arith", "what is 17 mod 5", 2], ["arith", "remainder when 17 is divided by 5", 2],
  ["alg", "solve for x: 2x + 3 = 11", 4], ["alg", "find x if 3x - 7 = 8", 5], ["alg", "what is x when 5x = 35", 7], ["alg", "x/4 = 3, find x", 12],
  ["alg", "solve x^2 - 5x + 6 = 0", { roots: [2, 3] }], ["alg", "find the roots of x^2 - 9", { roots: [3, -3] }], ["alg", "factor x^2 + 5x + 6", { re: /\(x \+ 2\).*\(x \+ 3\)|\(x \+ 3\).*\(x \+ 2\)/ }],
  ["alg", "expand (x + 2)(x - 3)", { expr: "x^2 - x - 6" }], ["alg", "expand (x+1)^3", { expr: "x^3+3x^2+3x+1" }], ["alg", "simplify 2x + 3x - x", { expr: "4x" }],
  ["alg", "solve 2x + y = 7 and x - y = 2", { re: /x = 3.*y = 1/ }], ["alg", "solve the system x + y = 10, x - y = 2", { re: /x = 6.*y = 4/ }],
  ["alg", "solve 2x + 5 > 11", { re: /3 < x|x > 3/ }], ["alg", "solve |x - 3| = 5", { roots: [8, -2] }], ["alg", "complete the square x^2 + 6x + 5", { re: /\(x \+ 3\)\^2 - 4/ }],
  ["alg", "vertex of y = x^2 - 4x + 3", { re: /2.*-1/ }], ["alg", "discriminant of x^2 + 4x + 5", -4], ["alg", "evaluate 3x^2 + 2 when x = 4", 50],
  ["alg", "f(x) = 2x + 1, find f(3)", 7], ["alg", "if f(x) = x^2 - 1 what is f(5)", 24], ["alg", "inverse of f(x) = 2x + 3", { expr: "(x-3)/2" }],
  ["alg", "slope of the line through (1, 2) and (3, 8)", 3], ["alg", "equation of the line through (1, 2) and (3, 8)", { re: /y = 3x - 1|y = 3 x - 1/ }],
  ["alg", "distance between (0, 0) and (3, 4)", 5], ["alg", "midpoint of (2, 4) and (6, 8)", { re: /4.*6/ }], ["alg", "y intercept of y = 2x + 5", { re: /\(0, 5\)/ }],
  ["alg", "solve 2^x = 32", 5], ["alg", "solve log(x) = 2", 100], ["alg", "rationalize 1/sqrt(2)", { re: /sqrt\(2\) ?\/ ?2|√2/ }],
  ["alg", "domain of 1/(x - 2)", { re: /2/ }], ["alg", "what is the sum of the roots of x^2 - 7x + 10", 7],
  ["geo", "area of a circle with radius 5", 25 * PI], ["geo", "circumference of a circle with diameter 10", 10 * PI], ["geo", "area of a triangle with base 6 and height 4", 12],
  ["geo", "hypotenuse of a right triangle with legs 3 and 4", 5], ["geo", "area of a rectangle 5 by 8", 40], ["geo", "perimeter of a rectangle with length 5 and width 3", 16],
  ["geo", "volume of a sphere with radius 3", 36 * PI], ["geo", "volume of a cylinder radius 2 height 5", 20 * PI], ["geo", "surface area of a cube with side 3", 54],
  ["geo", "sum of interior angles of a hexagon", 720], ["geo", "each interior angle of a regular octagon", 135], ["geo", "area of a triangle with sides 3, 4 and 5", 6],
  ["geo", "diagonal of a square with side 5", 5 * Math.SQRT2], ["geo", "area of a trapezoid with bases 4 and 6 and height 3", 15], ["geo", "convert 180 degrees to radians", PI],
  ["geo", "sin of 30 degrees", 0.5], ["geo", "cos 60 degrees", 0.5], ["geo", "what is tan 45 degrees", 1],
  ["calc", "derivative of x^3", { expr: "3x^2" }], ["calc", "differentiate sin(x) * x", { expr: "cos(x)*x + sin(x)" }], ["calc", "what's the derivative of e^(2x)", { expr: "2e^(2x)" }],
  ["calc", "integrate x^2", { anti: "x^3/3" }], ["calc", "integral of 1/x", { anti: "ln(x)" }], ["calc", "integrate x^2 from 0 to 3", 9],
  ["calc", "area under y = x^2 from 0 to 2", 8 / 3], ["calc", "limit of sin(x)/x as x approaches 0", 1], ["calc", "limit as x goes to infinity of (2x+1)/(x-3)", 2],
  ["calc", "slope of the tangent to y = x^2 at x = 3", 6], ["calc", "find the maximum of -x^2 + 4x", 4], ["calc", "critical points of x^3 - 3x", { roots: [1, -1] }],
  ["calc", "second derivative of x^4", { expr: "12x^2" }], ["calc", "d/dx ln(x^2)", { expr: "2/x" }], ["calc", "taylor series of e^x", { re: /x\^2 ?\/ ?2|x\^2\/2/ }],
  ["seq", "sum of the first 100 positive integers", 5050], ["seq", "next number in 2, 4, 8, 16", 32], ["seq", "10th term of the arithmetic sequence 3, 7, 11", 39],
  ["seq", "sum of the geometric series 1 + 1/2 + 1/4 + ...", 2], ["seq", "what is the 10th fibonacci number", 55],
  ["stats", "mean of 5 10 15 20", 12.5], ["stats", "median of 7, 1, 3, 9", 5], ["stats", "what's the range of 4, 9, 2, 7", 7],
  ["prob", "probability of rolling an even number on a die", 0.5], ["prob", "odds of flipping heads twice", 0.25], ["prob", "how many ways can 5 people sit in a row", 120],
  ["word", "a shirt costs 40 dollars and is on sale for 25% off. what is the sale price?", 30],
  ["word", "if 3 pencils cost 75 cents, how much do 7 pencils cost?", 175],
  ["word", "a car travels 150 miles in 3 hours. what is its average speed?", 50],
  ["word", "sam is 3 times as old as his son. in 10 years he will be twice as old. how old is the son now?", 10],
  ["word", "the sum of two numbers is 20 and their difference is 4. what are the numbers?", { re: /12.*8|8.*12/ }],
  ["word", "a rectangle has a perimeter of 30 and its length is twice its width. find the width", 5],
  ["word", "i have 5 apples and eat 2. how many are left?", 3],
  ["word", "what is the tax on a 50 dollar item at 8 percent", 4],
  ["word", "how long does it take to travel 240 km at 60 km per hour", 4],
  ["word", "a recipe needs 2 cups of flour for 12 cookies. how much flour for 30 cookies?", 5],
  ["new", "raise 250 by 20 percent", 300], ["new", "cut 90 by 10%", 81], ["new", "what is 20% more than 50", 60], ["new", "15 percent less than 200", 170],
  ["new", "convert 3/4 to decimal", 0.75], ["new", "express 0.2 as a percentage", 20], ["new", "what is 7/20 as a percent", 35], ["new", "multiplicative inverse of 2/3", 1.5],
  ["new", "evaluate x^2 - 3x at x = 5", 10], ["new", "find the value of 2a + 7 when a = 3", 13], ["new", "let g(t) = t^2 + 1, find g(2)", 5], ["new", "given h(x) = 3x - 4 what is h(10)", 26],
  ["new", "3x + 1 = 10, solve for x", 3], ["new", "2y - 4 = 10. find y", 7], ["new", "median of 10 20 30", 20], ["new", "standard deviation of 2 4 4 4 5 5 7 9", Math.sqrt(32 / 7)],
  ["new", "the 12th fibonacci number", 144], ["new", "2 + 1 + 1/2 + ...", 4], ["new", "sum of the infinite series 5 + 1 + 1/5 + ...", 6.25],
  ["new", "chance of rolling a number greater than 4 on a die", 1 / 3], ["new", "probability of getting an odd number on a fair die", 0.5], ["new", "probability of flipping 3 heads in a row", 0.125],
  ["new", "total cost of a 40 dollar jacket with 5% tax", 42], ["new", "tax on 200 dollars at 7.5 percent", 15],
  ["new", "how long does it take to drive 300 miles at 60 miles per hour", 5], ["new", "how far does a car travel in 3 hours at 50 km per hour", 150],
  ["new", "if 4 notebooks cost 300 cents, how much do 6 notebooks cost?", 450], ["new", "volume of a cone radius 3 height 4", 12 * PI],
  ["new", "ella is 4 times as old as her daughter. in 20 years she will be twice as old. how old is the daughter now?", 10],
  ["new", "the log of 100 squared", 4], ["new", "square root of 3 squared", 3],
];
